info:
  namespace: terraria
items:
#AXES
  copper_axe:
    display_name: display-name-copper_axe
    resource:
      material: STONE_AXE
      generate: true
      textures:
      - item/copper_axe
    durability:
      max_custom_durability: 150
    attribute_modifiers:
      mainhand:
        attackDamage: 7.5
        attackSpeed: 0.8
  tin_axe:
    display_name: display-name-tin_axe
    resource:
      material: STONE_AXE
      generate: true
      textures:
      - item/tin_axe
    durability:
      max_custom_durability: 175
    attribute_modifiers:
      mainhand:
        attackDamage: 8
        attackSpeed: 0.8
  lead_axe:
    display_name: display-name-lead_axe
    resource:
      material: IRON_AXE
      generate: true
      textures:
      - item/lead_axe
    durability:
      max_custom_durability: 200
    attribute_modifiers:
      mainhand:
        attackDamage: 8.5
        attackSpeed: 0.8
  iron_axe:
    display_name: display-name-iron_axe
    resource:
      material: IRON_AXE
    durability:
      max_custom_durability: 250
    attribute_modifiers:
      mainhand:
        attackDamage: 9
        attackSpeed: 0.9
  silver_axe:
    display_name: display-name-silver_axe
    resource:
      material: IRON_AXE
      generate: true
      textures:
      - item/silver_axe
    durability:
      max_custom_durability: 300
    attribute_modifiers:
      mainhand:
        attackDamage: 9.5
        attackSpeed: 0.9
  gold_axe:
    display_name: display-name-gold_axe
    resource:
      material: GOLDEN_AXE
    durability:
      max_custom_durability: 350
    attribute_modifiers:
      mainhand:
        attackDamage: 10
        attackSpeed: 0.9
  tungsten_axe:
    display_name: display-name-tungsten_axe
    resource:
      material: IRON_AXE
      generate: true
      textures:
      - item/tungsten_axe
    durability:
      max_custom_durability: 500
    attribute_modifiers:
      mainhand:
        attackDamage: 11
        attackSpeed: 0.9
  platinum_axe:
    display_name: display-name-platinum_axe
    resource:
      material: IRON_AXE
      generate: true
      textures:
      - item/platinum_axe
    durability:
      max_custom_durability: 1000
    attribute_modifiers:
      mainhand:
        attackDamage: 12
        attackSpeed: 0.9
  #---FACE 2
  meteorite_axe:
    display_name: display-name-meteorite_axe
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - item/meteorite_axe
    durability:
      max_custom_durability: 2100
    attribute_modifiers:
      mainhand:
        attackDamage: 15
        attackSpeed: 1
  hellstone_axe:
    display_name: display-name-hellstone_axe
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - item/hellstone_axe
    durability:
      max_custom_durability: 2100
    attribute_modifiers:
      mainhand:
        attackDamage: 16
        attackSpeed: 1
  crimson_axe:
    display_name: display-name-crimson_axe
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - item/crimson_axe
    durability:
      max_custom_durability: 2100
    attribute_modifiers:
      mainhand:
        attackDamage: 17
        attackSpeed: 1
  demonite_axe:
    display_name: display-name-demonite_axe
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
      - item/demonite_axe
    durability:
      max_custom_durability: 2100
    attribute_modifiers:
      mainhand:
        attackDamage: 18
        attackSpeed: 1
  #---FACE 3
  cobalt_axe:
    display_name: display-name-cobalt_axe
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - item/cobalt_axe
    durability:
      max_custom_durability: 2250
    attribute_modifiers:
      mainhand:
        attackDamage: 20
        attackSpeed: 1
  palladium_axe:
    display_name: display-name-palladium_axe
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - item/palladium_axe
    durability:
      max_custom_durability: 2250
    attribute_modifiers:
      mainhand:
        attackDamage: 21
        attackSpeed: 1
  orichalcum_axe:
    display_name: display-name-orichalcum_axe
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - item/orichalcum_axe
    durability:
      max_custom_durability: 2500
    attribute_modifiers:
      mainhand:
        attackDamage: 23
        attackSpeed: 1
  mythril_axe:
    display_name: display-name-mythril_axe
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - item/mythril_axe
    durability:
      max_custom_durability: 2500
    attribute_modifiers:
      mainhand:
        attackDamage: 24
        attackSpeed: 1
  adamantite_axe:
    display_name: display-name-adamantite_axe
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - item/adamantite_axe
    durability:
      max_custom_durability: 2750
    attribute_modifiers:
      mainhand:
        attackDamage: 26
        attackSpeed: 1
  titanium_axe:
    display_name: display-name-titanium_axe
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - item/titanium_axe
    attribute_modifiers:
      mainhand:
        attackDamage: 28
        attackSpeed: 1
  #---FACE 4
  chlorophyte_axe:
    display_name: display-name-chlorophyte_axe
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - item/chlorophyte_axe
    durability:
      max_custom_durability: 2900
    attribute_modifiers:
      mainhand:
        attackDamage: 33
        attackSpeed: 1
  #shroomite_axe
  luminite_axe:
    display_name: display-name-luminite_axe
    resource:
      material: NETHERITE_AXE
      generate: true
      textures:
      - item/luminite_axe
    durability:
      max_custom_durability: 3000
    attribute_modifiers:
      mainhand:
        attackDamage: 38
        attackSpeed: 1