info:
  namespace: terraria
  dictionary-lang: "tr"
dictionary:
# Blocks
  display-category-blocks: "&eBloklar"
  display-name-tin_ore: "&7Kalay Cevheri"
  display-name-lead_ore: "&7Kurşun Cevheri"
  display-name-silver_ore: "&7Gümüş Cevheri"
  display-name-tungsten_ore: "&9Tungsten Cevheri"
  display-name-platinum_ore: "&9Platin Cevheri"
  display-name-demonite_ore: "&5Şeytan Cevheri"
  display-name-meteorite_ore: "&5Meteor Cevheri"
  display-name-hellstone_ore: "&cCehennemtaşı Cevheri"
  display-name-cobalt_ore: "&aKobalt Cevheri"
  display-name-cobalt_ore_deepslate: "&aDerin Kayrak Kobalt Cevheri"
  display-name-palladium_ore: "&aPaladyum Cevheri"
  display-name-palladium_ore_deepslate: "&aDerin Kayrak Paladyum Cevheri"
  display-name-orichalcum_ore: "&aOrichalcum Cevheri"
  display-name-orichalcum_ore_deepslate: "&aDerin Kayrak Orichalcum Cevheri"
  display-name-mythril_ore: "&aMitril Cevheri"
  display-name-mythril_ore_deepslate: "&aDerin Kayrak Mitril Cevheri"
  display-name-adamantite_ore: "&aAdamantit Cevheri"
  display-name-adamantite_ore_deepslate: "&aDerin Kayrak Adamantit Cevheri"
  display-name-titanium_ore: "&aTitanyum Cevheri"
  display-name-titanium_ore_deepslate: "&aDerin Kayrak Titanyum Cevheri"
  display-name-chlorophyte_ore: "&6Klorofit Cevheri"
  display-name-chlorophyte_ore_deepslate: "&6Derin Kayrak Klorofit Cevheri"
  display-name-luminite_ore: "&6Luminit Cevheri"
# Ingots
  display-category-ingots: "&eKülçeler"
  display-name-tin_bar: "&7Kalay Külçesi"
  display-name-lead_bar: "&7Kurşun Külçesi"
  display-name-silver_bar: "&7Gümüş Külçesi"
  display-name-tungsten_bar: "&9Tungsten Külçesi"
  display-name-platinum_bar: "&9Platin Külçesi"
  display-name-demonite_bar: "&5Şeytan Külçesi"
  display-name-meteorite_bar: "&5Meteor Külçesi"
  display-name-hellstone_bar: "&cCehennemtaşı Külçesi"
  display-name-cobalt_bar: "&aKobalt Külçesi"
  display-name-palladium_bar: "&aPaladyum Külçesi"
  display-name-orichalcum_bar: "&aOrichalcum Külçesi"
  display-name-mythril_bar: "&aMitril Külçesi"
  display-name-adamantite_bar: "&aAdamantite Külçesi"
  display-name-titanium_bar: "&aTitanyum Külçesi"
  display-name-chlorophyte_bar: "&6Klorofit Külçesi"
  display-name-luminite_bar: "&6Luminit Külçesi"
# Swords
  display-category-swords: "&eKılıçlar"
  display-name-copper_sword: "&7Bakır Kılıç"
  display-name-tin_sword: "&7Kalay Kılıç"
  display-name-lead_sword: "&7Kurşun Kılıç"
  display-name-silver_sword: "&7Gümüş Kılıç"
  display-name-tungsten_sword: "&9Tungsten Kılıç"
  display-name-platinum_sword: "&9Platinyum Kılıç"
  display-name-demonite_sword: "&5Şeytan Kılıç"
  display-name-meteorite_sword: "&5Meteor Kılıç"
  display-name-hellstone_sword: "&cCehennemtaşı Kılıç"
  display-name-cobalt_sword: "&aKobalt Kılıç"
  display-name-palladium_sword: "&aPaladyum Kılıç"
  display-name-orichalcum_sword: "&aOrichalcum Kılıç"
  display-name-mythril_sword: "&aMythril Kılıç"
  display-name-adamantite_sword: "&aAdamantite Kılıç"
  display-name-titanium_sword: "&aMitril Kılıç"
  display-name-chlorophyte_sword: "&6Klorofit Kılıç"
  display-name-luminite_sword: "&6Luminit Kılıç"
# PickAxes
  display-category-pickaxes: "&eKazmalar"
  display-name-copper_pickaxe: "&7Bakır Kazma"
  display-name-tin_pickaxe: "&7Kalay Kazma"
  display-name-lead_pickaxe: "&7Kurşun Kazma"
  display-name-silver_pickaxe: "&7Gümüş Kazma"
  display-name-tungsten_pickaxe: "&9Tungsten Kazma"
  display-name-platinum_pickaxe: "&9Platinyum Kazma"
  display-name-demonite_pickaxe: "&5Şeytan Kazma"
  display-name-meteorite_pickaxe: "&5Meteor Kazma"
  display-name-hellstone_pickaxe: "&cCehennemtaşı Kazma"
  display-name-cobalt_pickaxe: "&aKobalt Kazma"
  display-name-palladium_pickaxe: "&aPaladyum Kazma"
  display-name-orichalcum_pickaxe: "&aOrichalcum Kazma"
  display-name-mythril_pickaxe: "&aMitril Kazma"
  display-name-adamantite_pickaxe: "&aAdamantite Kazma"
  display-name-titanium_pickaxe: "&aTitanyum Kazma"
  display-name-chlorophyte_pickaxe: "&6Klorofit Kazma"
  display-name-luminite_pickaxe: "&6Luminit Kazma"
# Axes
  display-category-axes: "&eBaltalar"
  display-name-copper_axe: "&7Bakır Balta"
  display-name-tin_axe: "&7Kalay Balta"
  display-name-lead_axe: "&7Kurşun Balta"
  display-name-silver_axe: "&7Gümüş Balta"
  display-name-tungsten_axe: "&9Tungsten Balta"
  display-name-platinum_axe: "&9Platinyum Balta"
  display-name-demonite_axe: "&5Şeytan Balta"
  display-name-meteorite_axe: "&5Meteor Balta"
  display-name-hellstone_axe: "&cCehennemtaşı Balta"
  display-name-cobalt_axe: "&aKobalt Balta"
  display-name-palladium_axe: "&aPaladyum Balta"
  display-name-orichalcum_axe: "&aOrichalcum Balta"
  display-name-mythril_axe: "&aMitril Balta"
  display-name-adamantite_axe: "&aAdamantit Balta"
  display-name-titanium_axe: "&aTitanyum Balta"
  display-name-chlorophyte_axe: "&6Klorofit Balta"
  display-name-luminite_axe: "&6Luminit Balta"
# Shovel
  display-category-shovels: "&eKürekler"
  display-name-copper_shovel: "&7Bakır Kürek"
  display-name-tin_shovel: "&7Kalay Kürek"
  display-name-lead_shovel: "&7Kurşun Kürek"
  display-name-silver_shovel: "&7Gümüş Kürek"
  display-name-tungsten_shovel: "&9Tungsten Kürek"
  display-name-platinum_shovel: "&9Platinyum Kürek"
  display-name-demonite_shovel: "&5Şeytan Kürek"
  display-name-meteorite_shovel: "&5Meteor Kürek"
  display-name-hellstone_shovel: "&cCehennemtaşı Kürek"
  display-name-cobalt_shovel: "&aKobalt Kürek"
  display-name-palladium_shovel: "&aPaladyum Kürek"
  display-name-orichalcum_shovel: "&aOrichalcum Kürek"
  display-name-mythril_shovel: "&aMitril Kürek"
  display-name-adamantite_shovel: "&aAdamantite Kürek"
  display-name-titanium_shovel: "&aTitanyum Kürek"
  display-name-chlorophyte_shovel: "&6Klorofit Kürek"
  display-name-luminite_shovel: "&6Luminit Kürek"
# Hoe
  display-category-hoes:  "&eHoes"
  display-name-copper_hoe: "&7Copper Hoe"
  display-name-tin_hoe: "&7Tin Hoe"
  display-name-lead_hoe: "&7Lead Hoe"
  display-name-silver_hoe: "&7Silver Hoe"
  display-name-tungsten_hoe: "&9Tungsten Hoe"
  display-name-platinum_hoe: "&9Platinum Hoe"
  display-name-demonite_hoe: "&5Demonite Hoe"
  display-name-meteorite_hoe: "&5Meteorite Hoe"
  display-name-hellstone_hoe: "&cHellstone Hoe"
  display-name-cobalt_hoe: "&aCobalt Hoe"
  display-name-palladium_hoe: "&aPalladium Hoe"
  display-name-orichalcum_hoe: "&aOrichalcum Hoe"
  display-name-mythril_hoe: "&aMythril Hoe"
  display-name-adamantite_hoe: "&aAdamantite Hoe"
  display-name-titanium_hoe: "&aTitanium Hoe"
  display-name-chlorophyte_hoe: "&6Chlorophyte Hoe"
  display-name-luminite_hoe: "&6Luminite Hoe"
# Armor
  display-category-armor: "&eZırhlar"
  display-name-copper_helmet: "&7Bakır Kask"
  display-name-copper_chest: "&7Bakır Göğüslük"
  display-name-copper_legs: "&7Bakır Pantolon"
  display-name-copper_boots: "&7Bakır Ayakkabı"
  display-name-tin_helmet: "&7Kalay Kask"
  display-name-tin_chest: "&7Kalay Göğüslük"
  display-name-tin_legs: "&7Kalay Pantolon"
  display-name-tin_boots: "&7Kalay Ayakkabı"
  display-name-lead_helmet: "&7Kurşun Kask"
  display-name-lead_chest: "&7Kurşun Göğüslük"
  display-name-lead_legs: "&7Kurşun Pantolon"
  display-name-lead_boots: "&7Kurşun Ayakkabı"
  display-name-silver_helmet: "&7Gümüş Kask"
  display-name-silver_chest: "&7Gümüş Göğüslük"
  display-name-silver_legs: "&7Gümüş Pantolon"
  display-name-silver_boots: "&7Gümüş Ayakkabı"
  display-name-tungsten_helmet: "&9Tungsten Kask"
  display-name-tungsten_chest: "&9Tungsten Göğüslük"
  display-name-tungsten_legs: "&9Tungsten Pantolon"
  display-name-tungsten_boots: "&9Tungsten Ayakkabı"
  display-name-platinum_helmet: "&9Platinyum Kask"
  display-name-platinum_chest: "&9Platinyum Göğüslük"
  display-name-platinum_legs: "&9Platinyum Pantolon"
  display-name-platinum_boots: "&9Platinyum Ayakkabı"
  display-name-demonite_helmet: "&5Şeytan Kask"
  display-name-demonite_chest: "&5Şeytan Göğüslük"
  display-name-demonite_legs: "&5Şeytan Pantolon"
  display-name-demonite_boots: "&5Şeytan Ayakkabı"
  display-name-meteorite_helmet: "&5Meteor Kask"
  display-name-meteorite_chest: "&5Meteor Göğüslük"
  display-name-meteorite_legs: "&5Meteor Pantolon"
  display-name-meteorite_boots: "&5Meteor Ayakkabı"
  display-name-hellstone_helmet: "&cCehennemtaşı Kask"
  display-name-hellstone_chest: "&cCehennemtaşı Göğüslük"
  display-name-hellstone_legs: "&cCehennemtaşı Pantolon"
  display-name-hellstone_boots: "&cCehennemtaşı Ayakkabı"
  display-name-cobalt_helmet: "&aKobalt Kask"
  display-name-cobalt_chest: "&aKobalt Göğüslük"
  display-name-cobalt_legs: "&aKobalt Pantolon"
  display-name-cobalt_boots: "&aKobalt Ayakkabı"
  display-name-palladium_helmet: "&aPaladyum Kask"
  display-name-palladium_chest: "&aPaladyum Göğüslük"
  display-name-palladium_legs: "&aPaladyum Pantolon"
  display-name-palladium_boots: "&aPaladyum Ayakkabı"
  display-name-orichalcum_helmet: "&aOrichalcum Kask"
  display-name-orichalcum_chest: "&aOrichalcum Göğüslük"
  display-name-orichalcum_legs: "&aOrichalcum Pantolon"
  display-name-orichalcum_boots: "&aOrichalcum Ayakkabı"
  display-name-mythril_helmet: "&aMitril Kask"
  display-name-mythril_chest: "&aMitril Göğüslük"
  display-name-mythril_legs: "&aMitril Pantolon"
  display-name-mythril_boots: "&aMitril Ayakkabı"
  display-name-adamantite_helmet: "&aAdamantit Kask"
  display-name-adamantite_chest: "&aAdamantit Göğüslük"
  display-name-adamantite_legs: "&aAdamantit Pantolon"
  display-name-adamantite_boots: "&aAdamantit Ayakkabı"
  display-name-titanium_helmet: "&aTitanyum Kask"
  display-name-titanium_chest: "&aTitanyum Göğüslük"
  display-name-titanium_legs: "&aTitanyum Pantolon"
  display-name-titanium_boots: "&aTitanyum Ayakkabı"
  display-name-chlorophyte_helmet: "&6Klorofit Kask"
  display-name-chlorophyte_chest: "&6Klorofit Göğüslük"
  display-name-chlorophyte_legs: "&6Klorofit Pantolon"
  display-name-chlorophyte_boots: "&6Klorofit Ayakkabı"
  display-name-luminite_helmet: "&6Luminit Kask"
  display-name-luminite_chest: "&6Luminit Göğüslük"
  display-name-luminite_legs: "&6Luminit Pantolon"
  display-name-luminite_boots: "&6Luminit Ayakkabı"
# Raw Materials
  display-category-raws: "&eHammaddeler"
  display-name-raw_tin: "&7Ham Kalay"
  display-name-raw_lead: "&7Ham Kurşun"
  display-name-raw_silver: "&7Ham Gümüş"
  display-name-raw_tungsten: "&9Ham Tungsten"
  display-name-raw_platinum: "&9Ham Platinyum"
  display-name-raw_demonite: "&5Ham Şeytan"
  display-name-raw_meteorite: "&5Ham Meteor"
  display-name-raw_hellstone: "&cHam Cehennemtaşı"
  display-name-raw_cobalt: "&aHam Kobalt"
  display-name-raw_palladium: "&aHam Paladyum"
  display-name-raw_orichalcum: "&aHam Orichalcum"
  display-name-raw_mythril: "&aHam Mitril"
  display-name-raw_adamantite: "&aHam Adamantite"
  display-name-raw_titanium: "&aHam Titanyum"
  display-name-raw_chlorophyte: "&6Ham Klorofit"
  display-name-raw_luminite: "&6Ham Luminit"
# Fish
  display-category-fish: "&eFish"
  display-name-atlantic_cod: "&eAtlantic Cod"
  display-name-bass: "&eBass"
  display-name-flounder: "&eFlounder"
  display-name-neon_tetra: "&eNeon Tetra"
  display-name-red_snapper: "&eRed Snapper"
  display-name-rock_lobster: "&eRock Lobster"
  display-name-shrimp: "&eShrimp"
  display-name-trout: "&eTrout"
  display-name-tuna: "&eTuna"
  display-name-armored_cavefish: "&eArmored Cavefish"
  display-name-blue_jellyfish: "&eBlue Jellyfish"
  display-name-crimson_tigerfish: "&eCrimson Tigerfish"
  display-name-damselfish: "&eDamselfish"
  display-name-double_cod: "&eDouble Cod"
  display-name-ebonkoi: "&eEbonkoi"
  display-name-frost_minnow: "&eFrost Minnow"
  display-name-green_jellyfish: "&eGreen Jellyfish"
  display-name-hemopiranha: "&eHemopiranha"
  display-name-honeyfin: "&eHoneyfin"
  display-name-pink_jellyfish: "&ePink Jellyfish"
  display-name-specular_fish: "&eSpecular Fish"
  display-name-stinkfish: "&eStinkfish"
  display-name-variegated_lardfish: "&eVariegated Lardfish"
  display-name-flarefin_koi: "&eFlarefin Koi"
  display-name-obsidifish: "&eObsidifish"
  display-name-princess_fish: "&ePrincess Fish"
  display-name-prismite: "&ePrismite"
  display-name-chaos_fish: "&eChaos Fish"
  display-name-golden_carp: "&eGolden Carp"
# Food
  display-category-food: "&eFood"
  display-name-cooked_fish: "&eCooked Fish"
  display-name-cooked_shrimp: "&eCooked Shrimp"
  display-name-seafood_dinner: "&eSeafood Dinner"
  display-name-lobster_tail: "&eLobster Tail"
  display-name-sashimi: "&eSashimi"
# Other
  display-category-others: "&eOthers"
  display-name-music_disc_frost_moon: "&bMusic Disk"
# Fishing
  display-category-fishing: "&eFishing"
  display-name-reinforced_fishing_rod: "&eReinforced Fishing Rod"
  display-name-fisher_of_souls: "&eFisher of Souls"
  display-name-fleshcatcher: "&eFleshcatcher"
  display-name-scarab_fishing_rod: "&eScarab Fishing Rod"
  display-name-chum_caster: "&eChum Caster"
  display-name-fiberglass_fishing_pole: "&eFiberglass Fishing Pole"
  display-name-mechanical_fishing_rod: "&eMechanicals Fishing Rod"
  display-name-sitting_ducks_fishing_pole: "&eSitting Duck's Fishing Pole"
  display-name-hotline_fishing_hook: "&eHotline Fishing Hook"
  display-name-golden_fishing_rod: "&eGolden Fishing Rod"