info:
  namespace: terraria
  dictionary-lang: "zh_cn"
dictionary:
# Blocks
  display-category-blocks: "&e矿石原矿"
  display-name-tin_ore: "&7锡矿石"
  display-name-lead_ore: "&7铅矿石"
  display-name-silver_ore: "&7银矿石"
  display-name-tungsten_ore: "&9钨矿石"
  display-name-platinum_ore: "&9铂矿石"
  display-name-demonite_ore: "&5魔矿石"
  display-name-meteorite_ore: "&5陨铁矿石"
  display-name-hellstone_ore: "&c炼狱矿石"
  display-name-cobalt_ore: "&a钴矿石"
  display-name-cobalt_ore_deepslate: "&a深层钴矿石"
  display-name-palladium_ore: "&a钯金矿石"
  display-name-palladium_ore_deepslate: "&a深层钯金矿"
  display-name-orichalcum_ore: "&a奥钢矿石"
  display-name-orichalcum_ore_deepslate: "&a深层奥钢矿石"
  display-name-mythril_ore: "&a秘银矿石"
  display-name-mythril_ore_deepslate: "&a深层秘银矿石"
  display-name-adamantite_ore: "&a精金矿石"
  display-name-adamantite_ore_deepslate: "&a深层精金矿石"
  display-name-titanium_ore: "&a钛矿石"
  display-name-titanium_ore_deepslate: "&a深层钛矿石"
  display-name-chlorophyte_ore: "&6叶绿矿石"
  display-name-chlorophyte_ore_deepslate: "&6深层叶绿矿石"
  display-name-luminite_ore: "&6夜明矿石"
# Ingots
  display-category-ingots: "&e矿物"
  display-name-tin_bar: "&7锡锭"
  display-name-lead_bar: "&7铅锭"
  display-name-silver_bar: "&7银锭"
  display-name-tungsten_bar: "&9钨锭"
  display-name-platinum_bar: "&9铂锭"
  display-name-demonite_bar: "&5魔石锭"
  display-name-meteorite_bar: "&5陨铁锭"
  display-name-hellstone_bar: "&c炼狱锭"
  display-name-cobalt_bar: "&a钴锭"
  display-name-palladium_bar: "&a钯金锭"
  display-name-orichalcum_bar: "&a奥钢锭"
  display-name-mythril_bar: "&a秘银锭"
  display-name-adamantite_bar: "&a精金锭"
  display-name-titanium_bar: "&a钛锭"
  display-name-chlorophyte_bar: "&6叶绿锭"
  display-name-luminite_bar: "&6夜明锭"
# Swords
  display-category-swords: "&e武器"
  display-name-copper_sword: "&7铜剑"
  display-name-tin_sword: "&7锡剑"
  display-name-lead_sword: "&7铅剑"
  display-name-silver_sword: "&7银剑"
  display-name-tungsten_sword: "&9钨剑"
  display-name-platinum_sword: "&9铂剑"
  display-name-demonite_sword: "&5魔石剑"
  display-name-meteorite_sword: "&5陨铁剑"
  display-name-hellstone_sword: "&c炼狱剑"
  display-name-cobalt_sword: "&a钴锭"
  display-name-palladium_sword: "&a钯金剑"
  display-name-orichalcum_sword: "&a奥钢剑"
  display-name-mythril_sword: "&a秘银剑"
  display-name-adamantite_sword: "&a精金剑"
  display-name-titanium_sword: "&a钛剑"
  display-name-chlorophyte_sword: "&6叶绿剑"
  display-name-luminite_sword: "&6夜明剑"
# PickAxes
  display-category-pickaxes: "&e稿子"
  display-name-copper_pickaxe: "&7铜稿"
  display-name-tin_pickaxe: "&7锡稿"
  display-name-lead_pickaxe: "&7铅稿"
  display-name-silver_pickaxe: "&7银稿"
  display-name-tungsten_pickaxe: "&9钨稿"
  display-name-platinum_pickaxe: "&9铂稿"
  display-name-demonite_pickaxe: "&5魔石稿"
  display-name-meteorite_pickaxe: "&5陨铁稿"
  display-name-hellstone_pickaxe: "&c炼狱稿"
  display-name-cobalt_pickaxe: "&a钴稿"
  display-name-palladium_pickaxe: "&a钯金稿"
  display-name-orichalcum_pickaxe: "&a奥钢稿"
  display-name-mythril_pickaxe: "&a秘银稿"
  display-name-adamantite_pickaxe: "&a精金稿"
  display-name-titanium_pickaxe: "&a钛稿"
  display-name-chlorophyte_pickaxe: "&6叶绿稿"
  display-name-luminite_pickaxe: "&6夜明稿"
# Axes
  display-category-axes: "&e斧头"
  display-name-copper_axe: "&7铜斧"
  display-name-tin_axe: "&7锡斧"
  display-name-lead_axe: "&7铅斧"
  display-name-silver_axe: "&7银斧"
  display-name-tungsten_axe: "&9钨斧"
  display-name-platinum_axe: "&9铂斧"
  display-name-demonite_axe: "&5魔石斧"
  display-name-meteorite_axe: "&5陨铁斧"
  display-name-hellstone_axe: "&c炼狱斧"
  display-name-cobalt_axe: "&a钴斧"
  display-name-palladium_axe: "&a钯金斧"
  display-name-orichalcum_axe: "&a奥钢斧"
  display-name-mythril_axe: "&a秘银斧"
  display-name-adamantite_axe: "&a精金斧"
  display-name-titanium_axe: "&a钛斧"
  display-name-chlorophyte_axe: "&6叶绿斧"
  display-name-luminite_axe: "&6夜明斧"
  # Shovel
  display-category-shovels: "&e铲"
  display-name-copper_shovel: "&7铜铲"
  display-name-tin_shovel: "&7锡铲"
  display-name-lead_shovel: "&7铅铲"
  display-name-silver_shovel: "&7银铲"
  display-name-tungsten_shovel: "&9钨铲"
  display-name-platinum_shovel: "&9铂铲"
  display-name-demonite_shovel: "&5魔石铲"
  display-name-meteorite_shovel: "&5陨铁铲"
  display-name-hellstone_shovel: "&c炼狱铲"
  display-name-cobalt_shovel: "&a钴铲"
  display-name-palladium_shovel: "&a钯金铲"
  display-name-orichalcum_shovel: "&a奥钢铲"
  display-name-mythril_shovel: "&a秘银铲"
  display-name-adamantite_shovel: "&a精金铲"
  display-name-titanium_shovel: "&a钛铲"
  display-name-chlorophyte_shovel: "&6叶绿铲"
  display-name-luminite_shovel: "&6夜明铲"
# Hoe
  display-category-hoes:  "&eHoes"
  display-name-copper_hoe: "&7Copper Hoe"
  display-name-tin_hoe: "&7Tin Hoe"
  display-name-lead_hoe: "&7Lead Hoe"
  display-name-silver_hoe: "&7Silver Hoe"
  display-name-tungsten_hoe: "&9Tungsten Hoe"
  display-name-platinum_hoe: "&9Platinum Hoe"
  display-name-demonite_hoe: "&5Demonite Hoe"
  display-name-meteorite_hoe: "&5Meteorite Hoe"
  display-name-hellstone_hoe: "&cHellstone Hoe"
  display-name-cobalt_hoe: "&aCobalt Hoe"
  display-name-palladium_hoe: "&aPalladium Hoe"
  display-name-orichalcum_hoe: "&aOrichalcum Hoe"
  display-name-mythril_hoe: "&aMythril Hoe"
  display-name-adamantite_hoe: "&aAdamantite Hoe"
  display-name-titanium_hoe: "&aTitanium Hoe"
  display-name-chlorophyte_hoe: "&6Chlorophyte Hoe"
  display-name-luminite_hoe: "&6Luminite Hoe"
# Armor
  display-category-armor: "&e盔甲"
  display-name-copper_helmet: "&7铜头盔"
  display-name-copper_chest: "&7铜胸甲"
  display-name-copper_legs: "&7铜护腿"
  display-name-copper_boots: "&7铜靴子"
  display-name-tin_helmet: "&7锡头盔"
  display-name-tin_chest: "&7锡胸甲"
  display-name-tin_legs: "&7锡护腿"
  display-name-tin_boots: "&7锡靴子"
  display-name-lead_helmet: "&7铅头盔"
  display-name-lead_chest: "&7铅胸甲"
  display-name-lead_legs: "&7铅护腿"
  display-name-lead_boots: "&7铅靴子"
  display-name-silver_helmet: "&7银头盔"
  display-name-silver_chest: "&7银胸甲"
  display-name-silver_legs: "&7银护腿"
  display-name-silver_boots: "&7银靴子"
  display-name-tungsten_helmet: "&9钨头盔"
  display-name-tungsten_chest: "&9钨胸甲"
  display-name-tungsten_legs: "&9钨护腿"
  display-name-tungsten_boots: "&9钨靴子"
  display-name-platinum_helmet: "&9铂头盔"
  display-name-platinum_chest: "&9铂胸甲"
  display-name-platinum_legs: "&9铂护腿"
  display-name-platinum_boots: "&9铂靴子"
  display-name-demonite_helmet: "&5魔石头盔"
  display-name-demonite_chest: "&5魔石胸甲"
  display-name-demonite_legs: "&5魔石护腿"
  display-name-demonite_boots: "&5魔石靴子"
  display-name-meteorite_helmet: "&5陨铁头盔"
  display-name-meteorite_chest: "&5陨铁胸甲"
  display-name-meteorite_legs: "&5陨铁护腿"
  display-name-meteorite_boots: "&5陨铁靴子"
  display-name-hellstone_helmet: "&c炼狱头盔"
  display-name-hellstone_chest: "&c炼狱胸甲"
  display-name-hellstone_legs: "&c炼狱护腿"
  display-name-hellstone_boots: "&c炼狱靴子"
  display-name-cobalt_helmet: "&a钴头盔"
  display-name-cobalt_chest: "&a钴胸甲"
  display-name-cobalt_legs: "&a钴护腿"
  display-name-cobalt_boots: "&a钴靴子"
  display-name-palladium_helmet: "&a钯金头盔"
  display-name-palladium_chest: "&a钯金胸甲"
  display-name-palladium_legs: "&a钯金护腿"
  display-name-palladium_boots: "&a钯金靴子"
  display-name-orichalcum_helmet: "&a奥钢头盔"
  display-name-orichalcum_chest: "&a奥钢胸甲"
  display-name-orichalcum_legs: "&a奥钢护腿"
  display-name-orichalcum_boots: "&a奥钢靴子"
  display-name-mythril_helmet: "&a秘银头盔"
  display-name-mythril_chest: "&a秘银胸甲"
  display-name-mythril_legs: "&a秘银护腿"
  display-name-mythril_boots: "&a秘银靴子"
  display-name-adamantite_helmet: "&a精金头盔"
  display-name-adamantite_chest: "&a精金胸甲"
  display-name-adamantite_legs: "&a精金护腿"
  display-name-adamantite_boots: "&a精金靴子"
  display-name-titanium_helmet: "&a钛头盔"
  display-name-titanium_chest: "&a钛胸甲"
  display-name-titanium_legs: "&a钛护腿"
  display-name-titanium_boots: "&a钛靴子"
  display-name-chlorophyte_helmet: "&6叶绿头盔"
  display-name-chlorophyte_chest: "&6叶绿胸甲"
  display-name-chlorophyte_legs: "&6叶绿护腿"
  display-name-chlorophyte_boots: "&6叶绿靴子"
  display-name-luminite_helmet: "&6夜明头盔"
  display-name-luminite_chest: "&6夜明胸甲"
  display-name-luminite_legs: "&6夜明护腿"
  display-name-luminite_boots: "&6夜明靴子"
#Raw Materials
  display-category-raws: "&e原材料"
  display-name-raw_tin: "&7粗锡矿"
  display-name-raw_lead: "&7粗铅矿"
  display-name-raw_silver: "&7粗银矿"
  display-name-raw_tungsten: "&9粗钨矿"
  display-name-raw_platinum: "&9粗铂矿"
  display-name-raw_demonite: "&5粗魔石"
  display-name-raw_meteorite: "&5粗陨铁"
  display-name-raw_hellstone: "&c粗炼狱矿"
  display-name-raw_cobalt: "&a粗钴矿"
  display-name-raw_palladium: "&a粗钯金矿"
  display-name-raw_orichalcum: "&a粗奥钢矿"
  display-name-raw_mythril: "&a粗秘银矿"
  display-name-raw_adamantite: "&a粗精金矿"
  display-name-raw_titanium: "&aRaw 粗钛矿"
  display-name-raw_chlorophyte: "&6粗叶绿矿"
  display-name-raw_luminite: "&6粗夜明矿"
# Fish
  display-category-fish: "&eFish"
  display-name-atlantic_cod: "&eAtlantic Cod"
  display-name-bass: "&eBass"
  display-name-flounder: "&eFlounder"
  display-name-neon_tetra: "&eNeon Tetra"
  display-name-red_snapper: "&eRed Snapper"
  display-name-rock_lobster: "&eRock Lobster"
  display-name-shrimp: "&eShrimp"
  display-name-trout: "&eTrout"
  display-name-tuna: "&eTuna"
  display-name-armored_cavefish: "&eArmored Cavefish"
  display-name-blue_jellyfish: "&eBlue Jellyfish"
  display-name-crimson_tigerfish: "&eCrimson Tigerfish"
  display-name-damselfish: "&eDamselfish"
  display-name-double_cod: "&eDouble Cod"
  display-name-ebonkoi: "&eEbonkoi"
  display-name-frost_minnow: "&eFrost Minnow"
  display-name-green_jellyfish: "&eGreen Jellyfish"
  display-name-hemopiranha: "&eHemopiranha"
  display-name-honeyfin: "&eHoneyfin"
  display-name-pink_jellyfish: "&ePink Jellyfish"
  display-name-specular_fish: "&eSpecular Fish"
  display-name-stinkfish: "&eStinkfish"
  display-name-variegated_lardfish: "&eVariegated Lardfish"
  display-name-flarefin_koi: "&eFlarefin Koi"
  display-name-obsidifish: "&eObsidifish"
  display-name-princess_fish: "&ePrincess Fish"
  display-name-prismite: "&ePrismite"
  display-name-chaos_fish: "&eChaos Fish"
  display-name-golden_carp: "&eGolden Carp"
# Food
  display-category-food: "&eFood"
  display-name-cooked_fish: "&eCooked Fish"
  display-name-cooked_shrimp: "&eCooked Shrimp"
  display-name-seafood_dinner: "&eSeafood Dinner"
  display-name-lobster_tail: "&eLobster Tail"
  display-name-sashimi: "&eSashimi"
# Other
  display-category-others: "&eOthers"
  display-name-music_disc_frost_moon: "&bMusic Disk"
# Fishing
  display-category-fishing: "&eFishing"
  display-name-reinforced_fishing_pole: "&eReinforced Fishing Rod"
  display-name-fisher_of_souls: "&eFisher of Souls"
  display-name-fleshcatcher: "&eFleshcatcher"
  display-name-scarab_fishing_rod: "&eScarab Fishing Rod"
  display-name-chum_caster: "&eChum Caster"
  display-name-fiberglass_fishing_pole: "&eFiberglass Fishing Pole"
  display-name-mechanical_fishing_rod: "&eMechanicals Fishing Rod"
  display-name-sitting_ducks_fishing_pole: "&eSitting Duck's Fishing Pole"
  display-name-hotline_fishing_hook: "&eHotline Fishing Hook"
  display-name-golden_fishing_rod: "&eGolden Fishing Rod"