info:
  namespace: terraria
  dictionary-lang: "fr"
dictionary:
  # Blocks
  display-category-blocks: "Blocs"
  display-name-tin_ore: "&7Minerai d'étain"
  display-name-lead_ore: "&7Minerai de plomb"
  display-name-silver_ore: "&7Minerai d'argent"
  display-name-tungsten_ore: "&9Minerai de tungstène"
  display-name-platinum_ore: "&9Minerai de platine"
  display-name-demonite_ore: "&5Minerai de démonite"
  display-name-meteorite_ore: "&5Minerai de météorite"
  display-name-hellstone_ore: "&cMinerai de pierre infernale"
  display-name-cobalt_ore: "&aMinerai de cobalt"
  display-name-cobalt_ore_deepslate: "&aMinerai de cobalt des abîmes"
  display-name-palladium_ore: "&aMinerai de palladium"
  display-name-palladium_ore_deepslate: "&aMinerai de palladium des abîmes"
  display-name-orichalcum_ore: "&aMinerai d'orichalque"
  display-name-orichalcum_ore_deepslate: "&aMinerai d'orichalque des abîmes"
  display-name-mythril_ore: "&aMinerai de mithril"
  display-name-mythril_ore_deepslate: "&aMinerai de mithril des abîmes"
  display-name-adamantite_ore: "&aMinerai d'adamantite"
  display-name-adamantite_ore_deepslate: "&aMinerai d'adamantite des abîmes"
  display-name-titanium_ore: "&aMinerai de titane"
  display-name-titanium_ore_deepslate: "&aMinerai de titane des abîmes"
  display-name-chlorophyte_ore: "&6Minerai de chlorophyte"
  display-name-chlorophyte_ore_deepslate: "&6Minerai de chlorophyte des abîmes"
  display-name-luminite_ore: "&6Minerai de luminite"
  # Ingots
  display-category-ingots: "Lingots"
  display-name-tin_bar: "&7Lingot d'étain"
  display-name-lead_bar: "&7Lingot de plomb"
  display-name-silver_bar: "&7Lingot d'Argent"
  display-name-tungsten_bar: "&9Lingot de Tungstène"
  display-name-platinum_bar: "&9Lingot de Platine"
  display-name-demonite_bar: "&5Lingot de Démonite"
  display-name-meteorite_bar: "&5Lingot de Météorite"
  display-name-hellstone_bar: "&cLingot de Pierre infernale"
  display-name-cobalt_bar: "&aLingot de Cobalt"
  display-name-palladium_bar: "&aLingot de Palladium"
  display-name-orichalcum_bar: "&aLingot d'orichalque"
  display-name-mythril_bar: "&aLingot de mithril"
  display-name-adamantite_bar: "&aLingot d'adamantite"
  display-name-titanium_bar: "&aLingot de titane"
  display-name-chlorophyte_bar: "&6Lingot de chlorophyte"
  display-name-luminite_bar: "&6Lingot de Luminite"
  # Swords
  display-category-swords: "Épées"
  display-name-copper_sword: "&7Épée en cuivre"
  display-name-tin_sword: "&7Épée en étain"
  display-name-lead_sword: "&7Épée en plomb"
  display-name-silver_sword: "&7Épée en argent"
  display-name-tungsten_sword: "&9Épée en tungstène"
  display-name-platinum_sword: "&9Épée en platine"
  display-name-demonite_sword: "&5Épée en démonite"
  display-name-meteorite_sword: "&5Épée en météorite"
  display-name-hellstone_sword: "&cÉpée en pierre infernale"
  display-name-cobalt_sword: "&aÉpée en cobalt"
  display-name-palladium_sword: "&aÉpée en palladium"
  display-name-orichalcum_sword: "&aÉpée en orichalque"
  display-name-mythril_sword: "&aÉpée en mithril"
  display-name-adamantite_sword: "&aÉpée en adamantite"
  display-name-titanium_sword: "&aÉpée en titane"
  display-name-chlorophyte_sword: "&6Épée en chlorophyte"
  display-name-luminite_sword: "&6Épée en luminite"
  # PickAxes
  display-category-pickaxes: "Pioches"
  display-name-copper_pickaxe: "&7Pioche en cuivre"
  display-name-tin_pickaxe: "&7Pioche en étain"
  display-name-lead_pickaxe: "&7Pioche en plomb"
  display-name-silver_pickaxe: "&7Pioche en plomb"
  display-name-tungsten_pickaxe: "&9Pioche en tungstène"
  display-name-platinum_pickaxe: "&9Pioche en platine"
  display-name-demonite_pickaxe: "&5Pioche en démonite"
  display-name-meteorite_pickaxe: "&5Pioche en météorite"
  display-name-hellstone_pickaxe: "&cPioche en pierre infernale"
  display-name-cobalt_pickaxe: "&aPioche en cobalt"
  display-name-palladium_pickaxe: "&aPioche en palladium"
  display-name-orichalcum_pickaxe: "&aPioche en orichalque"
  display-name-mythril_pickaxe: "&aPioche en mithril"
  display-name-adamantite_pickaxe: "&aPioche en adamantite"
  display-name-titanium_pickaxe: "&aPioche en titane"
  display-name-chlorophyte_pickaxe: "&6Pioche en chlorophyte"
  display-name-luminite_pickaxe: "&6Pioche en luminite"
  # Axes
  display-category-axes: "Haches"
  display-name-copper_axe: "&7Hache en Cuivre"
  display-name-tin_axe: "&7Hache en étain"
  display-name-lead_axe: "&7Hache en plomb"
  display-name-silver_axe: "&7Hache en argent"
  display-name-tungsten_axe: "&9Hache en tungstène"
  display-name-platinum_axe: "&9Hache en platine"
  display-name-demonite_axe: "&5Hache en démonite"
  display-name-meteorite_axe: "&5Hache en  météorite"
  display-name-hellstone_axe: "&cHache en pierre infernale"
  display-name-cobalt_axe: "&aHache en cobalt"
  display-name-palladium_axe: "&aHache en palladium"
  display-name-orichalcum_axe: "&aHache en orichalque"
  display-name-mythril_axe: "&aHache en mithril"
  display-name-adamantite_axe: "&aHache en adamantite"
  display-name-titanium_axe: "&aHache en titane"
  display-name-chlorophyte_axe: "&6Hache en chlorophyte"
  display-name-luminite_axe: "&6Hache en luminite"
  # Shovel
  display-category-shovels: "Pelles"
  display-name-copper_shovel: "&7Pelle en cuivre"
  display-name-tin_shovel: "&7Pelle en étain"
  display-name-lead_shovel: "&7Pelle en plomb"
  display-name-silver_shovel: "&7Pelle en argent"
  display-name-tungsten_shovel: "&9Pelle en tungstène"
  display-name-platinum_shovel: "&9Pelle en platine"
  display-name-demonite_shovel: "&5Pelle en démonite"
  display-name-meteorite_shovel: "&5Pelle en météorite"
  display-name-hellstone_shovel: "&cPelle en pierre infernale"
  display-name-cobalt_shovel: "&aPelle en cobalt"
  display-name-palladium_shovel: "&aPelle en palladium"
  display-name-orichalcum_shovel: "&aPelle en orichalque"
  display-name-mythril_shovel: "&aPelle en mithril"
  display-name-adamantite_shovel: "&aPelle en adamantite"
  display-name-titanium_shovel: "&aPelle en titane"
  display-name-chlorophyte_shovel: "&6Pelle en chlorophyte"
  display-name-luminite_shovel: "&6Pelle en luminite"
  # Armor
  display-category-armor: "Armures"
  display-name-copper_helmet: "&7Casque en cuivre"
  display-name-copper_chest: "&7Plastron en cuivre"
  display-name-copper_legs: "&7Jambières en cuivre"
  display-name-copper_boots: "&7Bottes en cuivre"
  display-name-tin_helmet: "&7Casque en étain"
  display-name-tin_chest: "&7Plastron en étain"
  display-name-tin_legs: "&7Jambières en étain"
  display-name-tin_boots: "&7Bottes en étain"
  display-name-lead_helmet: "&7Casque en plomb"
  display-name-lead_chest: "&7Plastron en plomb"
  display-name-lead_legs: "&7Jambières en plomb"
  display-name-lead_boots: "&7Bottes en plomb"
  display-name-silver_helmet: "&7Casque en argent"
  display-name-silver_chest: "&7Plastron en argent"
  display-name-silver_legs: "&7Jambières en argent"
  display-name-silver_boots: "&7Bottes en argent"
  display-name-tungsten_helmet: "&9Casque en tungstène"
  display-name-tungsten_chest: "&9Plastron en tungstène"
  display-name-tungsten_legs: "&9Jambières en tungstène"
  display-name-tungsten_boots: "&9Bottes en tungstène"
  display-name-platinum_helmet: "&9Casque en Platine"
  display-name-platinum_chest: "&9Plastron en platine"
  display-name-platinum_legs: "&9Jambières en platine"
  display-name-platinum_boots: "&9Bottes en platine"
  display-name-demonite_helmet: "&5Casque en démonite"
  display-name-demonite_chest: "&5Plastron en démonite"
  display-name-demonite_legs: "&5Jambières en démonite"
  display-name-demonite_boots: "&5Bottes en démonite"
  display-name-meteorite_helmet: "&5Casque en météorite"
  display-name-meteorite_chest: "&5Plastron en météorite"
  display-name-meteorite_legs: "&5Jambières en météorite"
  display-name-meteorite_boots: "&5Bottes en météorite"
  display-name-hellstone_helmet: "&cCasque en pierre infernale"
  display-name-hellstone_chest: "&cPlastron en pierre infernale"
  display-name-hellstone_legs: "&cJambières en pierre infernale"
  display-name-hellstone_boots: "&cBottes en pierre infernale"
  display-name-cobalt_helmet: "&aCasque en Cobalt"
  display-name-cobalt_chest: "&aPlastron en cobalt"
  display-name-cobalt_legs: "&aJambières en cobalt"
  display-name-cobalt_boots: "&aBottes en cobalt"
  display-name-palladium_helmet: "&aCasque en Palladium"
  display-name-palladium_chest: "&aPlastron en palladium"
  display-name-palladium_legs: "&aJambières en palladium"
  display-name-palladium_boots: "&aBottes en palladium"
  display-name-orichalcum_helmet: "&aCasque en orichalque"
  display-name-orichalcum_chest: "&aPlastron en orichalque"
  display-name-orichalcum_legs: "&aJambières en orichalque"
  display-name-orichalcum_boots: "&aBottes en orichalque"
  display-name-mythril_helmet: "&aCasque en mithril"
  display-name-mythril_chest: "&aPlastron en mithril"
  display-name-mythril_legs: "&aJambières en mithril"
  display-name-mythril_boots: "&aBottes en mithril"
  display-name-adamantite_helmet: "&aCasque en adamantite"
  display-name-adamantite_chest: "&aPlastron en adamantite"
  display-name-adamantite_legs: "&aJambières en adamantite"
  display-name-adamantite_boots: "&aBottes en adamantite"
  display-name-titanium_helmet: "&aCasque en titane"
  display-name-titanium_chest: "&aPlastron en titane"
  display-name-titanium_legs: "&aPlastron en titane"
  display-name-titanium_boots: "&aBottes en titane"
  display-name-chlorophyte_helmet: "&6Casque en chlorophyte"
  display-name-chlorophyte_chest: "&6Plastron en chlorophyte"
  display-name-chlorophyte_legs: "&6Jambières en chlorophyte"
  display-name-chlorophyte_boots: "&6Bottes en chlorophyte"
  display-name-luminite_helmet: "&6Casque en luminite"
  display-name-luminite_chest: "&6Plastron en luminite"
  display-name-luminite_legs: "&6Jambières en luminite"
  display-name-luminite_boots: "&6Bottes en luminite"
  #Raw Materials
  display-category-raws: "Matières Brutes"
  display-name-raw_tin: "&7Étain brut"
  display-name-raw_lead: "&7Plomb brut"
  display-name-raw_silver: "&7Argent brut"
  display-name-raw_tungsten: "&9Tungstène brut"
  display-name-raw_platinum: "&9Platine brut"
  display-name-raw_demonite: "&5Démonite brute"
  display-name-raw_meteorite: "&5Météorite brute"
  display-name-raw_hellstone: "&cPierre infernale brute"
  display-name-raw_cobalt: "&aCobalt brut"
  display-name-raw_palladium: "&aPalladium brut"
  display-name-raw_orichalcum: "&aOrichalque brut"
  display-name-raw_mythril: "&aMythril brut"
  display-name-raw_adamantite: "&aAdamantite brute"
  display-name-raw_titanium: "&aTitane brut"
  display-name-raw_chlorophyte: "&6Chlorophyte brut"
  display-name-raw_luminite: "&6Luminite brute"