info:
  namespace: terraria
  dictionary-lang: "en"
dictionary:
# Blocks
  display-category-blocks: "&eBlocks"
  display-name-tin_ore: "&7Tin Ore"
  display-name-lead_ore: "&7Lead Ore"
  display-name-silver_ore: "&7Silver Ore"
  display-name-tungsten_ore: "&9Tungsten Ore"
  display-name-platinum_ore: "&9Platinum Ore"
  display-name-demonite_ore: "&5Demonite Ore"
  display-name-meteorite_ore: "&5Meteorite Ore"
  display-name-hellstone_ore: "&cHellstone Ore"
  display-name-cobalt_ore: "&aCobalt Ore"
  display-name-cobalt_ore_deepslate: "&aDeepslate Cobalt Ore"
  display-name-palladium_ore: "&aPalladium Ore"
  display-name-palladium_ore_deepslate: "&aDeepslate Palladium Ore"
  display-name-orichalcum_ore: "&aOrichalcum Ore"
  display-name-orichalcum_ore_deepslate: "&aDeepslate Orichalcum Ore"
  display-name-mythril_ore: "&aMythril Ore"
  display-name-mythril_ore_deepslate: "&aDeepslate Mythril Ore"
  display-name-adamantite_ore: "&aAdamantite Ore"
  display-name-adamantite_ore_deepslate: "&aDeepslate Adamantite Ore"
  display-name-titanium_ore: "&aTitanium Ore"
  display-name-titanium_ore_deepslate: "&aDeepslate Titanium Ore"
  display-name-chlorophyte_ore: "&6Chlorophyte Ore"
  display-name-chlorophyte_ore_deepslate: "&6Deepslate Chlorophyte Ore"
  display-name-luminite_ore: "&6Luminite Ore"
# Ingots
  display-category-ingots: "&eIngots"
  display-name-tin_bar: "&7Tin Bar"
  display-name-lead_bar: "&7Lead Bar"
  display-name-silver_bar: "&7Silver Bar"
  display-name-tungsten_bar: "&9Tungsten Bar"
  display-name-platinum_bar: "&9Platinum Bar"
  display-name-demonite_bar: "&5Demonite Bar"
  display-name-meteorite_bar: "&5Meteorite Bar"
  display-name-hellstone_bar: "&cHellstone Bar"
  display-name-cobalt_bar: "&aCobalt Bar"
  display-name-palladium_bar: "&aPalladium Bar"
  display-name-orichalcum_bar: "&aOrichalcum Bar"
  display-name-mythril_bar: "&aMythril Bar"
  display-name-adamantite_bar: "&aAdamantite Bar"
  display-name-titanium_bar: "&aTitanium Bar"
  display-name-chlorophyte_bar: "&6Chlorophyte Bar"
  display-name-luminite_bar: "&6Luminite Bar"
# Swords
  display-category-swords: "&eSwords"
  display-name-copper_sword: "&7Copper Sword"
  display-name-tin_sword: "&7Tin Sword"
  display-name-lead_sword: "&7Lead Sword"
  display-name-silver_sword: "&7Silver Sword"
  display-name-tungsten_sword: "&9Tungsten Sword"
  display-name-platinum_sword: "&9Platinum Sword"
  display-name-demonite_sword: "&5Demonite Sword"
  display-name-meteorite_sword: "&5Meteorite Sword"
  display-name-hellstone_sword: "&cHellstone Sword"
  display-name-cobalt_sword: "&aCobalt Sword"
  display-name-palladium_sword: "&aPalladium Sword"
  display-name-orichalcum_sword: "&aOrichalcum Sword"
  display-name-mythril_sword: "&aMythril Sword"
  display-name-adamantite_sword: "&aAdamantite Sword"
  display-name-titanium_sword: "&aTitanium Sword"
  display-name-chlorophyte_sword: "&6Chlorophyte Sword"
  display-name-luminite_sword: "&6Luminite Sword"
# PickAxes
  display-category-pickaxes: "&ePickaxes"
  display-name-copper_pickaxe: "&7Copper Pickaxe"
  display-name-tin_pickaxe: "&7Tin Pickaxe"
  display-name-lead_pickaxe: "&7Lead Pickaxe"
  display-name-silver_pickaxe: "&7Silver Pickaxe"
  display-name-tungsten_pickaxe: "&9Tungsten Pickaxe"
  display-name-platinum_pickaxe: "&9Platinum Pickaxe"
  display-name-demonite_pickaxe: "&5Demonite Pickaxe"
  display-name-meteorite_pickaxe: "&5Meteorite Pickaxe"
  display-name-hellstone_pickaxe: "&cHellstone Pickaxe"
  display-name-cobalt_pickaxe: "&aCobalt Pickaxe"
  display-name-palladium_pickaxe: "&aPalladium Pickaxe"
  display-name-orichalcum_pickaxe: "&aOrichalcum Pickaxe"
  display-name-mythril_pickaxe: "&aMythril Pickaxe"
  display-name-adamantite_pickaxe: "&aAdamantite Pickaxe"
  display-name-titanium_pickaxe: "&aTitanium Pickaxe"
  display-name-chlorophyte_pickaxe: "&6Chlorophyte Pickaxe"
  display-name-luminite_pickaxe: "&6Luminite Pickaxe"
# Axes
  display-category-axes: "&eAxes"
  display-name-copper_axe: "&7Copper Axe"
  display-name-tin_axe: "&7Tin Axe"
  display-name-lead_axe: "&7Lead Axe"
  display-name-silver_axe: "&7Silver Axe"
  display-name-tungsten_axe: "&9Tungsten Axe"
  display-name-platinum_axe: "&9Platinum Axe"
  display-name-demonite_axe: "&5Demonite Axe"
  display-name-meteorite_axe: "&5Meteorite Axe"
  display-name-hellstone_axe: "&cHellstone Axe"
  display-name-cobalt_axe: "&aCobalt Axe"
  display-name-palladium_axe: "&aPalladium Axe"
  display-name-orichalcum_axe: "&aOrichalcum Axe"
  display-name-mythril_axe: "&aMythril Axe"
  display-name-adamantite_axe: "&aAdamantite Axe"
  display-name-titanium_axe: "&aTitanium Axe"
  display-name-chlorophyte_axe: "&6Chlorophyte Axe"
  display-name-luminite_axe: "&6Luminite Axe"
# Shovel
  display-category-shovels: "&eShovels"
  display-name-copper_shovel: "&7Copper Shovel"
  display-name-tin_shovel: "&7Tin Shovel"
  display-name-lead_shovel: "&7Lead Shovel"
  display-name-silver_shovel: "&7Silver Shovel"
  display-name-tungsten_shovel: "&9Tungsten Shovel"
  display-name-platinum_shovel: "&9Platinum Shovel"
  display-name-demonite_shovel: "&5Demonite Shovel"
  display-name-meteorite_shovel: "&5Meteorite Shovel"
  display-name-hellstone_shovel: "&cHellstone Shovel"
  display-name-cobalt_shovel: "&aCobalt Shovel"
  display-name-palladium_shovel: "&aPalladium Shovel"
  display-name-orichalcum_shovel: "&aOrichalcum Shovel"
  display-name-mythril_shovel: "&aMythril Shovel"
  display-name-adamantite_shovel: "&aAdamantite Shovel"
  display-name-titanium_shovel: "&aTitanium Shovel"
  display-name-chlorophyte_shovel: "&6Chlorophyte Shovel"
  display-name-luminite_shovel: "&6Luminite Shovel"
# Hoe
  display-category-hoes:  "&eHoes"
  display-name-copper_hoe: "&7Copper Hoe"
  display-name-tin_hoe: "&7Tin Hoe"
  display-name-lead_hoe: "&7Lead Hoe"
  display-name-silver_hoe: "&7Silver Hoe"
  display-name-tungsten_hoe: "&9Tungsten Hoe"
  display-name-platinum_hoe: "&9Platinum Hoe"
  display-name-demonite_hoe: "&5Demonite Hoe"
  display-name-meteorite_hoe: "&5Meteorite Hoe"
  display-name-hellstone_hoe: "&cHellstone Hoe"
  display-name-cobalt_hoe: "&aCobalt Hoe"
  display-name-palladium_hoe: "&aPalladium Hoe"
  display-name-orichalcum_hoe: "&aOrichalcum Hoe"
  display-name-mythril_hoe: "&aMythril Hoe"
  display-name-adamantite_hoe: "&aAdamantite Hoe"
  display-name-titanium_hoe: "&aTitanium Hoe"
  display-name-chlorophyte_hoe: "&6Chlorophyte Hoe"
  display-name-luminite_hoe: "&6Luminite Hoe"
# Armor
  display-category-armor: "&eArmor"
  display-name-copper_helmet: "&7Copper Helmet"
  display-name-copper_chest: "&7Copper Chestplate"
  display-name-copper_legs: "&7Copper Leggings"
  display-name-copper_boots: "&7Copper Boots"
  display-name-tin_helmet: "&7Tin Helmet"
  display-name-tin_chest: "&7Tin Chestplate"
  display-name-tin_legs: "&7Tin Leggings"
  display-name-tin_boots: "&7Tin Boots"
  display-name-lead_helmet: "&7Lead Helmet"
  display-name-lead_chest: "&7Lead Chestplate"
  display-name-lead_legs: "&7Lead Leggings"
  display-name-lead_boots: "&7Lead Boots"
  display-name-silver_helmet: "&7Silver Helmet"
  display-name-silver_chest: "&7Silver Chestplate"
  display-name-silver_legs: "&7Silver Leggings"
  display-name-silver_boots: "&7Silver Boots"
  display-name-tungsten_helmet: "&9Tungsten Helmet"
  display-name-tungsten_chest: "&9Tungsten Chestplate"
  display-name-tungsten_legs: "&9Tungsten Leggings"
  display-name-tungsten_boots: "&9Tungsten Boots"
  display-name-platinum_helmet: "&9Platinum Helmet"
  display-name-platinum_chest: "&9Platinum Chestplate"
  display-name-platinum_legs: "&9Platinum Leggings"
  display-name-platinum_boots: "&9Platinum Boots"
  display-name-demonite_helmet: "&5Demonite Helmet"
  display-name-demonite_chest: "&5Demonite Chestplate"
  display-name-demonite_legs: "&5Demonite Leggings"
  display-name-demonite_boots: "&5Demonite Boots"
  display-name-meteorite_helmet: "&5Meteorite Helmet"
  display-name-meteorite_chest: "&5Meteorite Chestplate"
  display-name-meteorite_legs: "&5Meteorite Leggings"
  display-name-meteorite_boots: "&5Meteorite Boots"
  display-name-hellstone_helmet: "&cHellstone Helmet"
  display-name-hellstone_chest: "&cHellstone Chestplate"
  display-name-hellstone_legs: "&cHellstone Leggings"
  display-name-hellstone_boots: "&cHellstone Boots"
  display-name-cobalt_helmet: "&aCobalt Helmet"
  display-name-cobalt_chest: "&aCobalt Chestplate"
  display-name-cobalt_legs: "&aCobalt Leggings"
  display-name-cobalt_boots: "&aCobalt Boots"
  display-name-palladium_helmet: "&aPalladium Helmet"
  display-name-palladium_chest: "&aPalladium Chestplate"
  display-name-palladium_legs: "&aPalladium Leggings"
  display-name-palladium_boots: "&aPalladium Boots"
  display-name-orichalcum_helmet: "&aOrichalcum Helmet"
  display-name-orichalcum_chest: "&aOrichalcum Chestplate"
  display-name-orichalcum_legs: "&aOrichalcum Leggings"
  display-name-orichalcum_boots: "&aOrichalcum Boots"
  display-name-mythril_helmet: "&aMythril Helmet"
  display-name-mythril_chest: "&aMythril Chestplate"
  display-name-mythril_legs: "&aMythril Leggings"
  display-name-mythril_boots: "&aMythril Boots"
  display-name-adamantite_helmet: "&aAdamantite Helmet"
  display-name-adamantite_chest: "&aAdamantite Chestplate"
  display-name-adamantite_legs: "&aAdamantite Leggings"
  display-name-adamantite_boots: "&aAdamantite Boots"
  display-name-titanium_helmet: "&aTitanium Helmet"
  display-name-titanium_chest: "&aTitanium Chestplate"
  display-name-titanium_legs: "&aTitanium Leggings"
  display-name-titanium_boots: "&aTitanium Boots"
  display-name-chlorophyte_helmet: "&6Chlorophyte Helmet"
  display-name-chlorophyte_chest: "&6Chlorophyte Chestplate"
  display-name-chlorophyte_legs: "&6Chlorophyte Leggings"
  display-name-chlorophyte_boots: "&6Chlorophyte Boots"
  display-name-luminite_helmet: "&6Luminite Helmet"
  display-name-luminite_chest: "&6Luminite Chestplate"
  display-name-luminite_legs: "&6Luminite Leggings"
  display-name-luminite_boots: "&6Luminite Boots"
#Raw Materials
  display-category-raws: "&eRaw Materials"
  display-name-raw_tin: "&7Raw Tin"
  display-name-raw_lead: "&7Raw Lead"
  display-name-raw_silver: "&7Raw Silver"
  display-name-raw_tungsten: "&9Raw Tungsten"
  display-name-raw_platinum: "&9Raw Platinum"
  display-name-raw_demonite: "&5Raw Demonite"
  display-name-raw_meteorite: "&5Raw Meteorite"
  display-name-raw_hellstone: "&cRaw Hellstone"
  display-name-raw_cobalt: "&aRaw Cobalt"
  display-name-raw_palladium: "&aRaw Palladium"
  display-name-raw_orichalcum: "&aRaw Orichalcum"
  display-name-raw_mythril: "&aRaw Mythril"
  display-name-raw_adamantite: "&aRaw Adamantite"
  display-name-raw_titanium: "&aRaw Titanium"
  display-name-raw_chlorophyte: "&6Raw Chlorophyte"
  display-name-raw_luminite: "&6Raw Luminite"
# Fish
  display-category-fish: "&eFish"
  display-name-atlantic_cod: "&eAtlantic Cod"
  display-name-bass: "&eBass"
  display-name-flounder: "&eFlounder"
  display-name-neon_tetra: "&eNeon Tetra"
  display-name-red_snapper: "&eRed Snapper"
  display-name-rock_lobster: "&eRock Lobster"
  display-name-shrimp: "&eShrimp"
  display-name-trout: "&eTrout"
  display-name-tuna: "&eTuna"
  display-name-armored_cavefish: "&eArmored Cavefish"
  display-name-blue_jellyfish: "&eBlue Jellyfish"
  display-name-crimson_tigerfish: "&eCrimson Tigerfish"
  display-name-damselfish: "&eDamselfish"
  display-name-double_cod: "&eDouble Cod"
  display-name-ebonkoi: "&eEbonkoi"
  display-name-frost_minnow: "&eFrost Minnow"
  display-name-green_jellyfish: "&eGreen Jellyfish"
  display-name-hemopiranha: "&eHemopiranha"
  display-name-honeyfin: "&eHoneyfin"
  display-name-pink_jellyfish: "&ePink Jellyfish"
  display-name-specular_fish: "&eSpecular Fish"
  display-name-stinkfish: "&eStinkfish"
  display-name-variegated_lardfish: "&eVariegated Lardfish"
  display-name-flarefin_koi: "&eFlarefin Koi"
  display-name-obsidifish: "&eObsidifish"
  display-name-princess_fish: "&ePrincess Fish"
  display-name-prismite: "&ePrismite"
  display-name-chaos_fish: "&eChaos Fish"
  display-name-golden_carp: "&eGolden Carp"
# Food
  display-category-food: "&eFood"
  display-name-cooked_fish: "&eCooked Fish"
  display-name-cooked_shrimp: "&eCooked Shrimp"
  display-name-seafood_dinner: "&eSeafood Dinner"
  display-name-lobster_tail: "&eLobster Tail"
  display-name-sashimi: "&eSashimi"
# Other
  display-category-others: "&eOthers"
  display-name-music_disc_frost_moon: "&bMusic Disk"