info:
  namespace: terraria
  dictionary-lang: "tr"
dictionary:
# Bloklar
  display-category-ores: "&eCevherler"
  display-name-tin_ore: "&7Kalay Cevheri"
  display-name-lead_ore: "&7Kurşun Cevheri"
  display-name-silver_ore: "&7Gümüş Cevheri"
  display-name-tungsten_ore: "&9Tungsten Cevheri"
  display-name-platinum_ore: "&9Platin Cevheri"
  display-name-crimson_ore: "&5Kızıl Cevheri"
  display-name-demonite_ore: "&5Şeytan Cevheri"
  display-name-meteorite_ore: "&5Meteor Cevheri"
  display-name-hellstone_ore: "&cCehennemtaşı Cevheri"
  display-name-cobalt_ore: "&aKobalt Cevheri"
  display-name-cobalt_ore_deepslate: "&aDerin Kayrak Kobalt Cevheri"
  display-name-palladium_ore: "&aPaladyum Cevheri"
  display-name-palladium_ore_deepslate: "&aDerin Kayrak Paladyum Cevheri"
  display-name-orichalcum_ore: "&aOrichalcum Cevheri"
  display-name-orichalcum_ore_deepslate: "&aDerin Kayrak Orichalcum Cevheri"
  display-name-mythril_ore: "&aMitril Cevheri"
  display-name-mythril_ore_deepslate: "&aDerin Kayrak Mitril Cevheri"
  display-name-adamantite_ore: "&aAdamantit Cevheri"
  display-name-adamantite_ore_deepslate: "&aDerin Kayrak Adamantit Cevheri"
  display-name-titanium_ore: "&aTitanyum Cevheri"
  display-name-titanium_ore_deepslate: "&aDerin Kayrak Titanyum Cevheri"
  display-name-chlorophyte_ore: "&6Klorofit Cevheri"
  display-name-chlorophyte_ore_deepslate: "&6Derin Kayrak Klorofit Cevheri"
  display-name-luminite_ore: "&6Luminit Cevheri"
# Külçeler
  display-category-ingots: "&eKülçeler"
  display-name-tin_bar: "&7Kalay Külçesi"
  display-name-lead_bar: "&7Kurşun Külçesi"
  display-name-silver_bar: "&7Gümüş Külçesi"
  display-name-tungsten_bar: "&9Tungsten Külçesi"
  display-name-platinum_bar: "&9Platin Külçesi"
  display-name-crimson_bar: "&5Kızıl Külçesi"
  display-name-demonite_bar: "&5Şeytan Külçesi"
  display-name-meteorite_bar: "&5Meteor Külçesi"
  display-name-hellstone_bar: "&cCehennemtaşı Külçesi"
  display-name-cobalt_bar: "&aKobalt Külçesi"
  display-name-palladium_bar: "&aPaladyum Külçesi"
  display-name-orichalcum_bar: "&aOrichalcum Külçesi"
  display-name-mythril_bar: "&aMitril Külçesi"
  display-name-adamantite_bar: "&aAdamantite Külçesi"
  display-name-titanium_bar: "&aTitanyum Külçesi"
  display-name-chlorophyte_bar: "&6Klorofit Külçesi"
  display-name-luminite_bar: "&6Luminit Külçesi"
# Kılıçlar
  display-category-swords: "&eKılıçlar"
  display-name-copper_sword: "&7Bakır Kılıç"
  display-name-tin_sword: "&7Kalay Kılıç"
  display-name-lead_sword: "&7Kurşun Kılıç"
  display-name-iron_sword: "&7Demir Kılıç"
  display-name-silver_sword: "&7Gümüş Kılıç"
  display-name-gold_sword: "&7Altın Kılıç"
  display-name-tungsten_sword: "&9Tungsten Kılıç"
  display-name-platinum_sword: "&9Platinyum Kılıç"
  display-name-crimson_sword: "&5Kızıl Kılıç"
  display-name-demonite_sword: "&5Şeytan Kılıç"
  display-name-meteorite_sword: "&5Meteor Kılıç"
  display-name-hellstone_sword: "&cCehennemtaşı Kılıç"
  display-name-cobalt_sword: "&aKobalt Kılıç"
  display-name-palladium_sword: "&aPaladyum Kılıç"
  display-name-orichalcum_sword: "&aOrichalcum Kılıç"
  display-name-mythril_sword: "&aMythril Kılıç"
  display-name-adamantite_sword: "&aAdamantite Kılıç"
  display-name-titanium_sword: "&aMitril Kılıç"
  display-name-chlorophyte_sword: "&6Klorofit Kılıç"
  display-name-luminite_sword: "&6Luminit Kılıç"
# Kazmalar
  display-category-pickaxes: "&eKazmalar"
  display-name-copper_pickaxe: "&7Bakır Kazma"
  display-name-tin_pickaxe: "&7Kalay Kazma"
  display-name-lead_pickaxe: "&7Kurşun Kazma"
  display-name-silver_pickaxe: "&7Gümüş Kazma"
  display-name-tungsten_pickaxe: "&9Tungsten Kazma"
  display-name-platinum_pickaxe: "&9Platinyum Kazma"
  display-name-crimson_pickaxe: "&5Kızıl Kazma"
  display-name-demonite_pickaxe: "&5Şeytan Kazma"
  display-name-meteorite_pickaxe: "&5Meteor Kazma"
  display-name-hellstone_pickaxe: "&cCehennemtaşı Kazma"
  display-name-cobalt_pickaxe: "&aKobalt Kazma"
  display-name-palladium_pickaxe: "&aPaladyum Kazma"
  display-name-orichalcum_pickaxe: "&aOrichalcum Kazma"
  display-name-mythril_pickaxe: "&aMitril Kazma"
  display-name-adamantite_pickaxe: "&aAdamantite Kazma"
  display-name-titanium_pickaxe: "&aTitanyum Kazma"
  display-name-chlorophyte_pickaxe: "&6Klorofit Kazma"
  display-name-luminite_pickaxe: "&6Luminit Kazma"
# Baltalar
  display-category-axes: "&eBaltalar"
  display-name-copper_axe: "&7Bakır Balta"
  display-name-tin_axe: "&7Kalay Balta"
  display-name-lead_axe: "&7Kurşun Balta"
  display-name-iron_axe: "&7Demir Balta"
  display-name-silver_axe: "&7Gümüş Balta"
  display-name-gold_axe: "&7Altın Balta"
  display-name-tungsten_axe: "&9Tungsten Balta"
  display-name-platinum_axe: "&9Platinyum Balta"
  display-name-crimson_axe: "&5Kızıl Balta"
  display-name-demonite_axe: "&5Şeytan Balta"
  display-name-meteorite_axe: "&5Meteor Balta"
  display-name-hellstone_axe: "&cCehennemtaşı Balta"
  display-name-cobalt_axe: "&aKobalt Balta"
  display-name-palladium_axe: "&aPaladyum Balta"
  display-name-orichalcum_axe: "&aOrichalcum Balta"
  display-name-mythril_axe: "&aMitril Balta"
  display-name-adamantite_axe: "&aAdamantit Balta"
  display-name-titanium_axe: "&aTitanyum Balta"
  display-name-chlorophyte_axe: "&6Klorofit Balta"
  display-name-luminite_axe: "&6Luminit Balta"
# Kürekler
  display-category-shovels: "&eKürekler"
  display-name-copper_shovel: "&7Bakır Kürek"
  display-name-tin_shovel: "&7Kalay Kürek"
  display-name-lead_shovel: "&7Kurşun Kürek"
  display-name-silver_shovel: "&7Gümüş Kürek"
  display-name-tungsten_shovel: "&9Tungsten Kürek"
  display-name-platinum_shovel: "&9Platinyum Kürek"
  display-name-crimson_shovel: "&5Kızıl Kürek"
  display-name-demonite_shovel: "&5Şeytan Kürek"
  display-name-meteorite_shovel: "&5Meteor Kürek"
  display-name-hellstone_shovel: "&cCehennemtaşı Kürek"
  display-name-cobalt_shovel: "&aKobalt Kürek"
  display-name-palladium_shovel: "&aPaladyum Kürek"
  display-name-orichalcum_shovel: "&aOrichalcum Kürek"
  display-name-mythril_shovel: "&aMitril Kürek"
  display-name-adamantite_shovel: "&aAdamantite Kürek"
  display-name-titanium_shovel: "&aTitanyum Kürek"
  display-name-chlorophyte_shovel: "&6Klorofit Kürek"
  display-name-luminite_shovel: "&6Luminit Kürek"
# Çapalar
  display-category-hoes:  "&eÇapalar"
  display-name-copper_hoe: "&7Bakır Çapa"
  display-name-tin_hoe: "&7Kalay Çapa"
  display-name-lead_hoe: "&7Kurşun Çapa"
  display-name-silver_hoe: "&7Gümüş Çapa"
  display-name-tungsten_hoe: "&9Tungsten Çapa"
  display-name-platinum_hoe: "&9Platinyum Çapa"
  display-name-crimson_hoe: "&5Kızıl Çapa"
  display-name-demonite_hoe: "&5Şeytan Çapa"
  display-name-meteorite_hoe: "&5Meteor Çapa"
  display-name-hellstone_hoe: "&cCehennemtaşı Çapa"
  display-name-cobalt_hoe: "&aKobalt Çapa"
  display-name-palladium_hoe: "&aPaladyum Çapa"
  display-name-orichalcum_hoe: "&aOrichalcum Çapa"
  display-name-mythril_hoe: "&aMitril Çapa"
  display-name-adamantite_hoe: "&aAdamantite Çapa"
  display-name-titanium_hoe: "&aTitanyum Çapa"
  display-name-chlorophyte_hoe: "&6Klorofit Çapa"
  display-name-luminite_hoe: "&6Luminit Çapa"
# Zırhlar
  display-category-armor: "&eZırhlar"
  display-name-copper_helmet: "&7Bakır Kask"
  display-name-copper_chest: "&7Bakır Göğüslük"
  display-name-copper_legs: "&7Bakır Pantolon"
  display-name-copper_boots: "&7Bakır Ayakkabı"
  display-name-tin_helmet: "&7Kalay Kask"
  display-name-tin_chest: "&7Kalay Göğüslük"
  display-name-tin_legs: "&7Kalay Pantolon"
  display-name-tin_boots: "&7Kalay Ayakkabı"
  display-name-lead_helmet: "&7Kurşun Kask"
  display-name-lead_chest: "&7Kurşun Göğüslük"
  display-name-lead_legs: "&7Kurşun Pantolon"
  display-name-lead_boots: "&7Kurşun Ayakkabı"
  display-name-iron_helmet: "&7Demir Kask"
  display-name-iron_chest: "&7Demir Göğüslük"
  display-name-iron_legs: "&7Demir Pantolon"
  display-name-iron_boots: "&7Demir Ayakkabı"
  display-name-silver_helmet: "&7Gümüş Kask"
  display-name-silver_chest: "&7Gümüş Göğüslük"
  display-name-silver_legs: "&7Gümüş Pantolon"
  display-name-silver_boots: "&7Gümüş Ayakkabı"
  display-name-gold_helmet: "&7Altın Kask"
  display-name-gold_chest: "&7Altın Göğüslük"
  display-name-gold_legs: "&7Altın Pantolon"
  display-name-gold_boots: "&7Altın Ayakkabı"
  display-name-tungsten_helmet: "&9Tungsten Kask"
  display-name-tungsten_chest: "&9Tungsten Göğüslük"
  display-name-tungsten_legs: "&9Tungsten Pantolon"
  display-name-tungsten_boots: "&9Tungsten Ayakkabı"
  display-name-platinum_helmet: "&9Platinyum Kask"
  display-name-platinum_chest: "&9Platinyum Göğüslük"
  display-name-platinum_legs: "&9Platinyum Pantolon"
  display-name-platinum_boots: "&9Platinyum Ayakkabı"
  display-name-demonite_helmet: "&5Şeytan Kask"
  display-name-demonite_chest: "&5Şeytan Göğüslük"
  display-name-demonite_legs: "&5Şeytan Pantolon"
  display-name-demonite_boots: "&5Şeytan Ayakkabı"
  display-name-meteorite_helmet: "&5Meteor Kask"
  display-name-meteorite_chest: "&5Meteor Göğüslük"
  display-name-meteorite_legs: "&5Meteor Pantolon"
  display-name-meteorite_boots: "&5Meteor Ayakkabı"
  display-name-hellstone_helmet: "&cCehennemtaşı Kask"
  display-name-hellstone_chest: "&cCehennemtaşı Göğüslük"
  display-name-hellstone_legs: "&cCehennemtaşı Pantolon"
  display-name-hellstone_boots: "&cCehennemtaşı Ayakkabı"
  display-name-crimson_helmet: "&5Kızıl Kask"
  display-name-crimson_chest: "&5Kızıl Göğüslük"
  display-name-crimson_legs: "&5Kızıl Pantolon"
  display-name-crimson_boots: "&5Kızıl Ayakkabı"
  display-name-cobalt_helmet: "&aKobalt Kask"
  display-name-cobalt_chest: "&aKobalt Göğüslük"
  display-name-cobalt_legs: "&aKobalt Pantolon"
  display-name-cobalt_boots: "&aKobalt Ayakkabı"
  display-name-palladium_helmet: "&aPaladyum Kask"
  display-name-palladium_chest: "&aPaladyum Göğüslük"
  display-name-palladium_legs: "&aPaladyum Pantolon"
  display-name-palladium_boots: "&aPaladyum Ayakkabı"
  display-name-orichalcum_helmet: "&aOrichalcum Kask"
  display-name-orichalcum_chest: "&aOrichalcum Göğüslük"
  display-name-orichalcum_legs: "&aOrichalcum Pantolon"
  display-name-orichalcum_boots: "&aOrichalcum Ayakkabı"
  display-name-mythril_helmet: "&aMitril Kask"
  display-name-mythril_chest: "&aMitril Göğüslük"
  display-name-mythril_legs: "&aMitril Pantolon"
  display-name-mythril_boots: "&aMitril Ayakkabı"
  display-name-adamantite_helmet: "&aAdamantit Kask"
  display-name-adamantite_chest: "&aAdamantit Göğüslük"
  display-name-adamantite_legs: "&aAdamantit Pantolon"
  display-name-adamantite_boots: "&aAdamantit Ayakkabı"
  display-name-titanium_helmet: "&aTitanyum Kask"
  display-name-titanium_chest: "&aTitanyum Göğüslük"
  display-name-titanium_legs: "&aTitanyum Pantolon"
  display-name-titanium_boots: "&aTitanyum Ayakkabı"
  display-name-chlorophyte_helmet: "&6Klorofit Kask"
  display-name-chlorophyte_chest: "&6Klorofit Göğüslük"
  display-name-chlorophyte_legs: "&6Klorofit Pantolon"
  display-name-chlorophyte_boots: "&6Klorofit Ayakkabı"
  display-name-luminite_helmet: "&6Luminit Kask"
  display-name-luminite_chest: "&6Luminit Göğüslük"
  display-name-luminite_legs: "&6Luminit Pantolon"
  display-name-luminite_boots: "&6Luminit Ayakkabı"
# Hammaddeler
  display-category-raws: "&eHammaddeler"
  display-name-raw_tin: "&7Ham Kalay"
  display-name-raw_lead: "&7Ham Kurşun"
  display-name-raw_silver: "&7Ham Gümüş"
  display-name-raw_tungsten: "&9Ham Tungsten"
  display-name-raw_platinum: "&9Ham Platinyum"
  display-name-raw_crimson: "&5Ham Kızıl"
  display-name-raw_demonite: "&5Ham Şeytan"
  display-name-raw_meteorite: "&5Ham Meteor"
  display-name-raw_hellstone: "&cHam Cehennemtaşı"
  display-name-raw_cobalt: "&aHam Kobalt"
  display-name-raw_palladium: "&aHam Paladyum"
  display-name-raw_orichalcum: "&aHam Orichalcum"
  display-name-raw_mythril: "&aHam Mitril"
  display-name-raw_adamantite: "&aHam Adamantite"
  display-name-raw_titanium: "&aHam Titanyum"
  display-name-raw_chlorophyte: "&6Ham Klorofit"
  display-name-raw_luminite: "&6Ham Luminit"
# Balıklar
  display-category-fish: "&eBalık"
  display-name-atlantic_cod: "&eAtlantik Balığı"
  display-name-bass: "&eLevrek"
  display-name-flounder: "&ePisi Balığı"
  display-name-neon_tetra: "&eNeon Tetra"
  display-name-red_snapper: "&eKırlangıç Balığı"
  display-name-rock_lobster: "&eKaya Istakozu"
  display-name-shrimp: "&eKarides"
  display-name-trout: "&eAlabalık"
  display-name-tuna: "&eTonbalığı"
  display-name-armored_cavefish: "&eZırhlı Mağara Balığı"
  display-name-blue_jellyfish: "&eMavi Denizanası"
  display-name-crimson_tigerfish: "&eKızıl Kaplan Balığı"
  display-name-damselfish: "&eDamselfish"
  display-name-double_cod: "&eÇift Morina"
  display-name-ebonkoi: "&eEbonkoi"
  display-name-frost_minnow: "&eBuz Minnow"
  display-name-green_jellyfish: "&eYeşil Denizanası"
  display-name-hemopiranha: "&eHemopirana"
  display-name-honeyfin: "&eBal Yüzgeci"
  display-name-pink_jellyfish: "&ePembe Denizanası"
  display-name-specular_fish: "&eAynalı Balık"
  display-name-stinkfish: "&eKokuşmuş Balık"
  display-name-variegated_lardfish: "&eAlacalı Lardfish"
  display-name-flarefin_koi: "&eFlarefin Koi"
  display-name-obsidifish: "&eObsidif Balık"
  display-name-princess_fish: "&ePrenses Balık"
  display-name-prismite: "&ePrizmit"
  display-name-chaos_fish: "&eKaos Balığı"
  display-name-golden_carp: "&eAltın Sazan"
# Yemekler
  display-category-food: "&eYemek"
  display-name-cooked_fish: "&ePişmiş Balık"
  display-name-cooked_shrimp: "&ePişmiş Karides"
  display-name-seafood_dinner: "&eDeniz Ürünleri Akşam Yemeği"
  display-name-lobster_tail: "&eIstakoz Kuyruğu"
  display-name-sashimi: "&eSashimi"
# Diğer
  display-category-others: "&eDiğerleri"
  display-name-music_disc_frost_moon: "&bMüzik Diski"
# Oltalar
  display-category-fishing: "&eOltalar"
  display-name-reinforced_fishing_pole: "&eTakviyeli Olta"
  display-name-fisher_of_souls: "&eRuhların Balıkçısı"
  display-name-fleshcatcher: "&eEt Avcısı"
  display-name-scarab_fishing_rod: "&eBokböceği Olta"
  display-name-chum_caster: "&eChum Caster"
  display-name-fiberglass_fishing_pole: "&eFiberglas Olta Kamışı"
  display-name-mechanical_fishing_rod: "&eMekanik Olta"
  display-name-sitting_ducks_fishing_pole: "&eOturan Ördek Oltası"
  display-name-hotline_fishing_hook: "&eYardım Hattı Olta Kancası"
  display-name-golden_fishing_rod: "&eAltın Olta"
# Açıklama
  lore-can_fish_in_lava: "&cLavda balık tutabilir"
  lore-fish-common: "&7Her yerde bulunan en yaygın balık."
  lore-fish-common-ocean: "&7Okyanusta bulunan yaygın balık."
  lore-fish-common-jungle: "&7Nemli biyomlarda bulunan yaygın balık."
  lore-fish-common-desert: "&7Sıcak biyomlarda bulunan yaygın balık."
  lore-fish-common-ice: "&7Soğuk biyomlarda bulunan yaygın balık."
  lore-fish-uncommon-ocean: "&9Okyanusta bulunan nadir balık"
  lore-fish-uncommon-jungle: "&9Nemli biyomlarda bulunan nadir balık."
  lore-fish-uncommon-ice: "&9Soğuk biyomlarda bulunan nadir balık."
  lore-fish-uncommon-underground: "&9Yeraltında bulunan nadir balık."
  lore-fish-uncommon-jungle_underground: "&9Nemli biyomlarda yeraltında bulunan nadir balık."
  lore-fish-uncommon-cavern: "&9Mağaralarda bulunan nadir balık."
  lore-fish-uncommon-crimson: "&9Kızıl biyomlarda bulunan nadir balık."
  lore-fish-uncommon-corruption: "&9Corruption biyomlarında bulunan nadir balık."
  lore-fish-uncommon-sky: "&9Yüksek rakımlarda bulunan nadir balık."
  lore-fish-uncommon-honey: "&9Balda balık tutarken bulunan nadir balık."
  lore-fish-rare-hell: "&aNetherda bulunan nadir balık."
  lore-fish-rare-hallow: "&aGölette bulunan nadir balık."
  lore-fish-very_rare-hallow: "&bÇukurda bulunan çok nadir balık."
  lore-fish-legendary_underground: "&6Efsanevi balık yeraltında bulundu."
  lore-fish-legendary-hallow_underground: "&6Efsanevi balık çukurda yeraltında bulundu."
  lore-fish-neon_tetra: "&3&oRenkli pullarıyla iyi fiyata satılabilir."
  lore-fish-rock_lobster: "&3&oAma o bir kaya değildi!"
  lore-fish-golden_carp: "&3Oldukça parlak. Bu muhtemelen iyi fiyat eder."
# Bloklar
  display-category-blocks: "&eBloklar"
  display-name-tin_block: "&7Kalay Blok"
  display-name-lead_block: "&7Kurşun Blok"
  display-name-silver_block: "&7Gümüş Blok"
  display-name-tungsten_block: "&7Tungsten Blok"
  display-name-platinum_block: "&7Platinyum Block"
  display-name-meteorite_block: "&7Meteor Block"
  display-name-crimson_block: "&7Kızıl Blok"
  display-name-demonite_block: "&7Şeytani Blok"
  display-name-hellstone_block: "&7Cehennemtaşı Blok"
  display-name-cobalt_block: "&7Kobalt Block"
  display-name-palladium_block: "&7Paladyum Blok"
  display-name-mythril_block: "&7Mitril Blok"
  display-name-orichalcum_block: "&7Orichalcum Blok"
  display-name-adamantite_block: "&7Adamantite Blok"
  display-name-titanium_block: "&7Titanyum Blok"
  display-name-chlorophyte_block: "&7Klorofit Blok"
  display-name-luminite_block: "&7Luminit Blok"  
