info:
  namespace: terraria
  dictionary-lang: "es"
dictionary:
  # Blocks
  display-category-blocks: "&eBloques"
  display-name-tin_ore: "&7Mineral de Estaño"
  display-name-lead_ore: "&7Mineral de Plomo"
  display-name-silver_ore: "&7Mineral de Plata"
  display-name-tungsten_ore: "&9Mineral de Tungsteno"
  display-name-platinum_ore: "&9Mineral de Platino"
  display-name-demonite_ore: "&5Mineral de Demonio"
  display-name-meteorite_ore: "&5Mineral de Meteorito"
  display-name-hellstone_ore: "&cMineral de Piedra Infernal"
  display-name-cobalt_ore: "&aMineral de Cobalto"
  display-name-cobalt_ore_deepslate: "&aMineral de Cobalto (DeepSlate)"
  display-name-palladium_ore: "&aMineral de Paladio"
  display-name-palladium_ore_deepslate: "&aMineral de Paladio (DeepSlate)"
  display-name-orichalcum_ore: "&aMineral de Oricalco"
  display-name-orichalcum_ore_deepslate: "&aMineral de Oricalco (Deepslate)"
  display-name-mythril_ore: "&aMineral de Mitril"
  display-name-mythril_ore_deepslate: "&aMineral de Mitril (DeepSlate)"
  display-name-adamantite_ore: "&aMineral de Adamantita"
  display-name-adamantite_ore_deepslate: "&aMineral de Adamantita (DeepSlate)"
  display-name-titanium_ore: "&aMineral de Titanio"
  display-name-titanium_ore_deepslate: "&aMineral de Titanio (DeepSlate)"
  display-name-chlorophyte_ore: "&6Mineral de Clorofita"
  display-name-chlorophyte_ore_deepslate: "&6Mineral de Clorofita (DeepSlate)"
  display-name-luminite_ore: "&6Mineral de Lumen"
  # Ingots
  display-category-ingots: "&eLingotes"
  display-name-tin_bar: "&7Lingote de Estaño"
  display-name-lead_bar: "&7Lingote de Plomo"
  display-name-silver_bar: "&7Lingote de Plata"
  display-name-tungsten_bar: "&9Lingote de Tungsteno"
  display-name-platinum_bar: "&9Lingote de Platino"
  display-name-demonite_bar: "&5Lingote de Demonio"
  display-name-meteorite_bar: "&5Lingote de Meteorito"
  display-name-hellstone_bar: "&cLingote de Piedra Infernal"
  display-name-cobalt_bar: "&aLingote de Cobalto"
  display-name-palladium_bar: "&aLingote de Paladio"
  display-name-orichalcum_bar: "&aLingote de Oricalco"
  display-name-mythril_bar: "&aLingote de Mitril"
  display-name-adamantite_bar: "&aLingote de Adamantita"
  display-name-titanium_bar: "&aLingote de Titanio"
  display-name-chlorophyte_bar: "&6Lingote de Clorofita"
  display-name-luminite_bar: "&6Lingote de Lumen"
  # Swords
  display-category-swords: "&eEspadas"
  display-name-copper_sword: "&7Espada de Cobre"
  display-name-tin_sword: "&7Espada de Estaño"
  display-name-lead_sword: "&7Espada de Plomo"
  display-name-silver_sword: "&7Espada de Plata"
  display-name-tungsten_sword: "&9Espada de Tungsteno"
  display-name-platinum_sword: "&9Espada de Platino"
  display-name-demonite_sword: "&5Espada Endemoniada"
  display-name-meteorite_sword: "&5Espada de Meteorito"
  display-name-hellstone_sword: "&cEspada Fundida"
  display-name-cobalt_sword: "&aEspada de Cobalto"
  display-name-palladium_sword: "&aEspada de Paladio"
  display-name-orichalcum_sword: "&aEspada de Oricalco"
  display-name-mythril_sword: "&aEspada de Mitril"
  display-name-adamantite_sword: "&aEspada de Adamantita"
  display-name-titanium_sword: "&aEspada de Titanio"
  display-name-chlorophyte_sword: "&6Espada de Clorofita"
  display-name-luminite_sword: "&6Espada de Lumen"
  # PickAxes
  display-category-pickaxes: "&ePicos"
  display-name-copper_pickaxe: "&7Pico de Cobre"
  display-name-tin_pickaxe: "&7Pico de Estaño"
  display-name-lead_pickaxe: "&7Pico de Plomo"
  display-name-silver_pickaxe: "&7Pico de Plata"
  display-name-tungsten_pickaxe: "&9Pico de Tungsteno"
  display-name-platinum_pickaxe: "&9Pico de Platino"
  display-name-demonite_pickaxe: "&5Pico Endemoniado"
  display-name-meteorite_pickaxe: "&5Pico de Meteorito"
  display-name-hellstone_pickaxe: "&cPico Fundido"
  display-name-cobalt_pickaxe: "&aPico de Cobalto"
  display-name-palladium_pickaxe: "&aPico de Paladio"
  display-name-mythril_pickaxe: "&aPico de Mitril"
  display-name-orichalcum_pickaxe: "&aPico de Oricalco"
  display-name-adamantite_pickaxe: "&aPico de Adamantita"
  display-name-titanium_pickaxe: "&aPico de Titanio"
  display-name-chlorophyte_pickaxe: "&6Pico de Clorofita"
  display-name-luminite_pickaxe: "&6Pico de Lumen"
  # Axes
  display-category-axes: "&eHachas"
  display-name-copper_axe: "&7Hacha de Cobre"
  display-name-tin_axe: "&7Hacha de Estaño"
  display-name-lead_axe: "&7Hacha de Plomo"
  display-name-silver_axe: "&7Hacha de Plata"
  display-name-tungsten_axe: "&9Hacha de Tungsteno"
  display-name-platinum_axe: "&9Hacha de Platino"
  display-name-demonite_axe: "&5Hacha Endemoniada"
  display-name-meteorite_axe: "&5Hacha de Meteorito"
  display-name-hellstone_axe: "&cHacha Fundida"
  display-name-cobalt_axe: "&aHacha de Cobalto"
  display-name-palladium_axe: "&aHacha de Paladio"
  display-name-mythril_axe: "&aHacha de Mitril"
  display-name-orichalcum_axe: "&aHacha de Oricalco"
  display-name-adamantite_axe: "&aHacha de Adamantita"
  display-name-titanium_axe: "&aHacha de Titanio"
  display-name-chlorophyte_axe: "&6Hacha de Clorofita"
  display-name-luminite_axe: "&6Hacha de Lumen"
  # Shovels
  display-category-shovels: "&ePalas"
  display-name-copper_shovel: "&7Pala de Cobre"
  display-name-tin_shovel: "&7Pala de Estaño"
  display-name-lead_shovel: "&7Pala de Plomo"
  display-name-silver_shovel: "&7Pala de Plata"
  display-name-tungsten_shovel: "&9Pala de Tungsteno"
  display-name-platinum_shovel: "&9Pala de Platino"
  display-name-demonite_shovel: "&5Pala Endemoniada"
  display-name-meteorite_shovel: "&5Pala de Meteorito"
  display-name-hellstone_shovel: "&cPala Fundida"
  display-name-cobalt_shovel: "&aPala de Cobalto"
  display-name-palladium_shovel: "&aPala de Paladio"
  display-name-mythril_shovel: "&aPala de Mitril"
  display-name-orichalcum_shovel: "&aPala de Oricalco"
  display-name-adamantite_shovel: "&aPala de Adamantita"
  display-name-titanium_shovel: "&aPala de Titanio"
  display-name-chlorophyte_shovel: "&6Pala de Clorofita"
  display-name-luminite_shovel: "&6Pala de Lumen"
  # Hoes
  display-category-hoes:  "&eAzadas"
  display-name-copper_hoe: "&7Copper Azada"
  display-name-tin_hoe: "&7Tin Azada"
  display-name-lead_hoe: "&7Lead Azada"
  display-name-silver_hoe: "&7Silver Azada"
  display-name-tungsten_hoe: "&9Tungsten Azada"
  display-name-platinum_hoe: "&9Platinum Azada"
  display-name-demonite_hoe: "&5Demonite Azada"
  display-name-meteorite_hoe: "&5Meteorite Azada"
  display-name-hellstone_hoe: "&cHellstone Azada"
  display-name-cobalt_hoe: "&aCobalt Azada"
  display-name-palladium_hoe: "&aPalladium Azada"
  display-name-orichalcum_hoe: "&aOrichalcum Azada"
  display-name-mythril_hoe: "&aMythril Azada"
  display-name-adamantite_hoe: "&aAdamantite Azada"
  display-name-titanium_hoe: "&aTitanium Azada"
  display-name-chlorophyte_hoe: "&6Chlorophyte Azada"
  display-name-luminite_hoe: "&6Luminite Azada"
  # Armors
  display-category-armors: "&eArmaduras"
  display-name-copper_helmet: "&7Casco de Cobre"
  display-name-copper_chest: "&7Coraza de Cobre"
  display-name-copper_legs: "&7Pantalones de Cobre"
  display-name-copper_boots: "&7Botas de Cobre"
  display-name-tin_helmet: "&7Casco de Estaño"
  display-name-tin_chest: "&7Coraza de Estaño"
  display-name-tin_legs: "&7Pantalones de Estaño"
  display-name-tin_boots: "&7Botas de Estaño"
  display-name-lead_helmet: "&7Casco de Plomo"
  display-name-lead_chest: "&7Coraza de Plomo"
  display-name-lead_legs: "&7Pantalones de Plomo"
  display-name-lead_boots: "&7Botas de Plomo"
  display-name-silver_helmet: "&7Casco de Plata"
  display-name-silver_chest: "&7Coraza de Plata"
  display-name-silver_legs: "&7Pantalones de Plata"
  display-name-silver_boots: "&7Botas de Plata"
  display-name-tungsten_helmet: "&9Casco de Tungsteno"
  display-name-tungsten_chest: "&9Coraza de Tungsteno"
  display-name-tungsten_legs: "&9Pantalones de Tungsteno"
  display-name-tungsten_boots: "&9Botas de Tungsteno"
  display-name-platinum_helmet: "&9Casco de Platino"
  display-name-platinum_chest: "&9Coraza de Platino"
  display-name-platinum_legs: "&9Pantalones de Platino"
  display-name-platinum_boots: "&9Botas de Platino"
  display-name-demonite_helmet: "&5Casco Endemoniado"
  display-name-demonite_chest: "&5Coraza Endemoniada"
  display-name-demonite_legs: "&5Pantalones Endemoniados"
  display-name-demonite_boots: "&5Botas Endemoniadas"
  display-name-meteorite_helmet: "&5Casco de Meteorito"
  display-name-meteorite_chest: "&5Coraza de Meteorito"
  display-name-meteorite_legs: "&5Pantalones de Meteorito"
  display-name-meteorite_boots: "&cBotas de Meteorito"
  display-name-hellstone_helmet: "&cCasco Fundido"
  display-name-hellstone_chest: "&cCoraza Fundida"
  display-name-hellstone_legs: "&cPantalones Fundidos"
  display-name-hellstone_boots: "&5Botas Fundidas"
  display-name-cobalt_helmet: "&aCasco de Cobalto"
  display-name-cobalt_chest: "&aCoraza de Cobalto"
  display-name-cobalt_legs: "&aPantalones de Cobalto"
  display-name-cobalt_boots: "&aBotas de Cobalto"
  display-name-palladium_helmet: "&aCasco de Paladio"
  display-name-palladium_chest: "&aCoraza de Paladio"
  display-name-palladium_legs: "&aPantalones de Paladio"
  display-name-palladium_boots: "&aBotas de Paladio"
  display-name-mythril_helmet: "&aCasco de Mitril"
  display-name-mythril_chest: "&aCoraza de Mitril"
  display-name-mythril_legs: "&aPantalones de Mitril"
  display-name-mythril_boots: "&aBotas de Mitril"
  display-name-orichalcum_helmet: "&aCasco de Oricalco"
  display-name-orichalcum_chest: "&aCoraza de Oricalco"
  display-name-orichalcum_legs: "&aPantalones de Oricalco"
  display-name-orichalcum_boots: "&aBotas de Oricalco"
  display-name-adamantite_helmet: "&aCasco de Adamantita"
  display-name-adamantite_chest: "&aCoraza de Adamantita"
  display-name-adamantite_legs: "&aPantalones de Adamantita"
  display-name-adamantite_boots: "&aBotas de Adamantita"
  display-name-titanium_helmet: "&aCasco de Titanio"
  display-name-titanium_chest: "&aCoraza de Titanio"
  display-name-titanium_legs: "&aPantalones de Titanio"
  display-name-titanium_boots: "&aBotas de Titanio"
  display-name-chlorophyte_helmet: "&6Casco de Clorofita"
  display-name-chlorophyte_chest: "&6Coraza de Clorofita"
  display-name-chlorophyte_legs: "&6Pantalones de Clorofita"
  display-name-chlorophyte_boots: "&6Botas de Clorofita"
  display-name-luminite_helmet: "&6Casco de Lumen"
  display-name-luminite_chest: "&6Coraza de Lumen"
  display-name-luminite_legs: "&6Pantalones de Lumen"
  display-name-luminite_boots: "&6Botas de Lumen"
# Materiales Crudos
  display-category-raws: "&eMateriales Crudos"
  display-name-raw_tin: "&7Estaño Crudo"
  display-name-raw_lead: "&7Plomo Crudo"
  display-name-raw_silver: "&7Plata Cruda"
  display-name-raw_tungsten: "&9Tungsteno Crudo"
  display-name-raw_platinum: "&9Platino Crudo"
  display-name-raw_demonite: "&5Endemoniado Crudo"
  display-name-raw_meteorite: "&5Meteorito Crudo"
  display-name-raw_hellstone: "&cFundido Crudo"
  display-name-raw_cobalt: "&aCobalto Crudo"
  display-name-raw_palladium: "&aPaladio Crudo"
  display-name-raw_mythril: "&aMitril Crudo"
  display-name-raw_orichalcum: "&aOricalco Crudo"
  display-name-raw_adamantite: "&aAdamantita Cruda"
  display-name-raw_titanium: "&aTitanio Crudo"
  display-name-raw_chlorophyte: "&6Clorofita Cruda"
  display-name-raw_luminite: "&6Lumen Crudo"
# Discos de Musica
  display-category-others: "&eOtros"
  display-name-music_disc_frost_moon: "&bDisco de Musica"


