info:
  namespace: terraria
categories:
  blocks:
    enabled: true 
    skip_if_already: false
    icon: terraria:cobalt_ore
    name: display-category-blocks
    items:
      - terraria:tin_ore
      - terraria:lead_ore
      - terraria:silver_ore
      - terraria:platinum_ore
      - terraria:tungsten_ore
      - terraria:demonite_ore
      - terraria:hellstone_ore
      - terraria:meteorite_ore
      - terraria:cobalt_ore
      - terraria:cobalt_ore_deepslate
      - terraria:palladium_ore
      - terraria:palladium_ore_deepslate
      - terraria:orichalcum_ore
      - terraria:orichalcum_ore_deepslate
      - terraria:mythril_ore
      - terraria:mythril_ore_deepslate
      - terraria:adamantite_ore
      - terraria:adamantite_ore_deepslate
      - terraria:titanium_ore
      - terraria:titanium_ore_deepslate
      - terraria:chlorophyte_ore
      - terraria:chlorophyte_ore_deepslate
      - terraria:luminite_ore
  swords:
    enabled: true 
    skip_if_already: false
    icon: terraria:palladium_sword
    name: display-category-swords
    items:
      - terraria:copper_sword
      - terraria:tin_sword
      - terraria:lead_sword
      - terraria:silver_sword
      - terraria:platinum_sword
      - terraria:tungsten_sword
      - terraria:demonite_sword
      - terraria:hellstone_sword
      - terraria:meteorite_sword
      - terraria:cobalt_sword
      - terraria:palladium_sword
      - terraria:orichalcum_sword
      - terraria:mythril_sword
      - terraria:adamantite_sword
      - terraria:titanium_sword
      - terraria:chlorophyte_sword
      - terraria:luminite_sword
  pickaxes:
    enabled: true 
    skip_if_already: false
    icon: terraria:demonite_pickaxe
    name: display-category-pickaxes
    items:
      - terraria:copper_pickaxe
      - terraria:tin_pickaxe
      - terraria:lead_pickaxe
      - terraria:silver_pickaxe
      - terraria:platinum_pickaxe
      - terraria:tungsten_pickaxe
      - terraria:demonite_pickaxe
      - terraria:hellstone_pickaxe
      - terraria:meteorite_pickaxe
      - terraria:cobalt_pickaxe
      - terraria:palladium_pickaxe
      - terraria:orichalcum_pickaxe
      - terraria:mythril_pickaxe
      - terraria:adamantite_pickaxe
      - terraria:titanium_pickaxe
      - terraria:chlorophyte_pickaxe
      - terraria:luminite_pickaxe
  axes:
    enabled: true 
    skip_if_already: false
    icon: terraria:mythril_axe
    name: display-category-axes
    items:
      - terraria:copper_axe
      - terraria:tin_axe
      - terraria:lead_axe
      - terraria:silver_axe
      - terraria:platinum_axe
      - terraria:tungsten_axe
      - terraria:demonite_axe
      - terraria:hellstone_axe
      - terraria:meteorite_axe
      - terraria:cobalt_axe
      - terraria:palladium_axe
      - terraria:orichalcum_axe
      - terraria:mythril_axe
      - terraria:adamantite_axe
      - terraria:titanium_axe
      - terraria:chlorophyte_axe
      - terraria:luminite_axe
  shovels:
    enabled: true 
    skip_if_already: false
    icon: terraria:adamantite_shovel
    name: display-category-shovels
    items:
      - terraria:copper_shovel
      - terraria:tin_shovel
      - terraria:lead_shovel
      - terraria:silver_shovel
      - terraria:platinum_shovel
      - terraria:tungsten_shovel
      - terraria:demonite_shovel
      - terraria:hellstone_shovel
      - terraria:meteorite_shovel
      - terraria:cobalt_shovel
      - terraria:palladium_shovel
      - terraria:orichalcum_shovel
      - terraria:mythril_shovel
      - terraria:adamantite_shovel
      - terraria:titanium_shovel
      - terraria:chlorophyte_shovel
      - terraria:luminite_shovel
  hoes:
    enabled: true 
    skip_if_already: false
    icon: terraria:mythril_hoe
    name: display-category-hoes
    items:
      - terraria:copper_hoe
      - terraria:tin_hoe
      - terraria:lead_hoe
      - terraria:silver_hoe
      - terraria:platinum_hoe
      - terraria:tungsten_hoe
      - terraria:demonite_hoe
      - terraria:hellstone_hoe
      - terraria:meteorite_hoe
      - terraria:cobalt_hoe
      - terraria:palladium_hoe
      - terraria:orichalcum_hoe
      - terraria:mythril_hoe
      - terraria:adamantite_hoe
      - terraria:titanium_hoe
      - terraria:chlorophyte_hoe
      - terraria:luminite_hoe
  ingots:
    enabled: true 
    skip_if_already: false
    icon: terraria:tungsten_bar
    name: display-category-ingots
    items:
      - terraria:tin_bar
      - terraria:lead_bar
      - terraria:silver_bar
      - terraria:platinum_bar
      - terraria:tungsten_bar
      - terraria:demonite_bar
      - terraria:hellstone_bar
      - terraria:meteorite_bar
      - terraria:cobalt_bar
      - terraria:palladium_bar
      - terraria:orichalcum_bar
      - terraria:mythril_bar
      - terraria:adamantite_bar
      - terraria:titanium_bar
      - terraria:chlorophyte_bar
      - terraria:luminite_bar
  raws:
    enabled: true
    skip_if_already: false
    icon: terraria:raw_tin
    name: display-category-raws
    items:
      - terraria:raw_tin
      - terraria:raw_lead
      - terraria:raw_silver
      - terraria:raw_tungsten
      - terraria:raw_platinum
      - terraria:raw_demonite
      - terraria:raw_hellstone
      - terraria:raw_meteorite
      - terraria:raw_cobalt
      - terraria:raw_palladium
      - terraria:raw_orichalcum
      - terraria:raw_mythril
      - terraria:raw_adamantite
      - terraria:raw_titanium
      - terraria:raw_chlorophyte
      - terraria:raw_luminite
  armor:
    enabled: true
    skip_if_already: false
    icon: terraria:mythril_helmet
    name: display-category-armors
    items:
      - terraria:copper_helmet
      - terraria:copper_chest
      - terraria:copper_legs
      - terraria:copper_boots
      - terraria:tin_helmet
      - terraria:tin_chest
      - terraria:tin_legs
      - terraria:tin_boots
      - terraria:lead_helmet
      - terraria:lead_chest
      - terraria:lead_legs
      - terraria:lead_boots
      - terraria:silver_helmet
      - terraria:silver_chest
      - terraria:silver_legs
      - terraria:silver_boots
      - terraria:platinum_helmet
      - terraria:platinum_chest
      - terraria:platinum_legs
      - terraria:platinum_boots
      - terraria:tungsten_helmet
      - terraria:tungsten_chest
      - terraria:tungsten_legs
      - terraria:tungsten_boots
      - terraria:demonite_helmet
      - terraria:demonite_chest
      - terraria:demonite_legs
      - terraria:demonite_boots
      - terraria:hellstone_helmet
      - terraria:hellstone_chest
      - terraria:hellstone_legs
      - terraria:hellstone_boots
      - terraria:meteorite_helmet
      - terraria:meteorite_chest
      - terraria:meteorite_legs
      - terraria:meteorite_boots
      - terraria:cobalt_helmet
      - terraria:cobalt_chest
      - terraria:cobalt_legs
      - terraria:cobalt_boots
      - terraria:palladium_helmet
      - terraria:palladium_chest
      - terraria:palladium_legs
      - terraria:palladium_boots
      - terraria:orichalcum_helmet
      - terraria:orichalcum_chest
      - terraria:orichalcum_legs
      - terraria:orichalcum_boots
      - terraria:mythril_helmet
      - terraria:mythril_chest
      - terraria:mythril_legs
      - terraria:mythril_boots
      - terraria:adamantite_helmet
      - terraria:adamantite_chest
      - terraria:adamantite_legs
      - terraria:adamantite_boots
      - terraria:titanium_helmet
      - terraria:titanium_chest
      - terraria:titanium_legs
      - terraria:titanium_boots
      - terraria:chlorophyte_helmet
      - terraria:chlorophyte_chest
      - terraria:chlorophyte_legs
      - terraria:chlorophyte_boots
      - terraria:luminite_helmet
      - terraria:luminite_chest
      - terraria:luminite_legs
      - terraria:luminite_boots
  fishing:
    enabled: true 
    skip_if_already: false
    icon: terraria:bass
    name: display-category-fishing
    items:
      - terraria:reinforced_fishing_pole
      - terraria:fisher_of_souls
      - terraria:fleshcatcher
      - terraria:scarab_fishing_rod
      - terraria:chum_caster
      - terraria:fiberglass_fishing_pole
      - terraria:mechanical_fishing_rod
      - terraria:sitting_ducks_fishing_pole
      - terraria:hotline_fishing_hook
      - terraria:golden_fishing_rod
  fish:
    enabled: true 
    skip_if_already: false
    icon: terraria:bass
    name: display-category-fish
    items:
      - terraria:atlantic_cod
      - terraria:bass
      - terraria:flounder
      - terraria:neon_tetra
      - terraria:red_snapper
      - terraria:rock_lobster
      - terraria:shrimp
      - terraria:trout
      - terraria:tuna
      - terraria:armored_cavefish
      - terraria:blue_jellyfish
      - terraria:crimson_tigerfish
      - terraria:damselfish
      - terraria:double_cod
      - terraria:ebonkoi
      - terraria:frost_minnow
      - terraria:green_jellyfish
      - terraria:hemopiranha
      - terraria:honeyfin
      - terraria:pink_jellyfish
      - terraria:specular_fish
      - terraria:stinkfish
      - terraria:variegated_lardfish
      - terraria:flarefin_koi
      - terraria:obsidifish
      - terraria:princess_fish
      - terraria:prismite
      - terraria:chaos_fish
      - terraria:golden_carp
  food:
    enabled: true 
    skip_if_already: false
    icon: terraria:seafood_dinner
    name: display-category-food
    items:
      - terraria:cooked_fish
      - terraria:cooked_shrimp
      - terraria:seafood_dinner
      - terraria:lobster_tail
      - terraria:sashimi
  other:
    enabled: true 
    skip_if_already: false
    icon: terraria:music_disc_frost_moon
    name: display-category-others
    items:
      - terraria:music_disc_frost_moon