info:
  namespace: terraria
worlds_populators:
  tin_ore:
    block: tin_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
    chunk_chance: 80.0
    max_height: 45
    min_height: 5
    vein_blocks: 4
    chunk_veins: 2
  lead_ore:
    block: lead_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
    chunk_chance: 80.0
    max_height: 45
    min_height: 5
    vein_blocks: 4
    chunk_veins: 2
  silver_ore:
    block: silver_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
    chunk_chance: 75.0
    max_height: 50
    min_height: 10
    vein_blocks: 4
    chunk_veins: 2
  tungsten_ore:
    block: tungsten_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
    chunk_chance: 75.0
    max_height: 50
    min_height: 10
    vein_blocks: 4
    chunk_veins: 2
  platinum_ore:
    block: platinum_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
    chunk_chance: 60.0
    max_height: 40
    min_height: 0
    vein_blocks: 3
    chunk_veins: 2
  demonite_ore:
    block: demonite_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
#    biomes:
#    - MUSHROOM_FIELDS
    chunk_chance: 50.0
    max_height: 100
    min_height: 0
    vein_blocks: 3
    chunk_veins: 1
  meteorite_ore:
    block: meteorite_ore
    worlds:
    - world
    replaceable_blocks:
    - PACKED_ICE
    - SNOW_BLOCK
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
#    biomes:
#    - STONY_PEAKS
#    - JAGGED_PEALS
#    - FROZEN_PEAKS
    chunk_chance: 80.0
    max_height: 319
    min_height: 62
    vein_blocks: 1
    chunk_veins: 1
  hellstone_ore:
    block: hellstone_ore
    worlds:
    - world_nether
    replaceable_blocks:
    - NETHERRACK
    chunk_chance: 50.0
    max_height: 100
    min_height: 0
    vein_blocks: 1
    chunk_veins: 1
  cobalt_ore:
    block: cobalt_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
#    biomes:
#    - DRIPSTONE_CAVES
    chunk_chance: 50.0
    max_height: 100
    min_height: 1
    vein_blocks: 3
    chunk_veins: 1
  cobalt_ore_deepslate:
    block: cobalt_ore_deepslate
    worlds:
    - world
    replaceable_blocks:
    - DEEPSLATE
    - TUFF
#    biomes:
#    - DRIPSTONE_CAVES
    chunk_chance: 50.0
    max_height: 0
    min_height: -64
    vein_blocks: 3
    chunk_veins: 1
  palladium_ore:
    block: palladium_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
#    biomes:
#    - DRIPSTONE_CAVES
    chunk_chance: 50.0
    max_height: 100
    min_height: 1
    vein_blocks: 3
    chunk_veins: 1
  palladium_ore_deepslate:
    block: palladium_ore_deepslate
    worlds:
    - world
    replaceable_blocks:
    - DEEPSLATE
    - TUFF
#    biomes:
#    - DRIPSTONE_CAVES
    chunk_chance: 50.0
    max_height: 0
    min_height: -64
    vein_blocks: 3
    chunk_veins: 1
  orichalcum_ore:
    block: orichalcum_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
#    biomes:
#    - LUSH_CAVES
    chunk_chance: 50.0
    max_height: 100
    min_height: 1
    vein_blocks: 3
    chunk_veins: 1
  orichalcum_ore_deepslate:
    block: orichalcum_ore_deepslate
    worlds:
    - world
    replaceable_blocks:
    - DEEPSLATE
    - TUFF
#    biomes:
#    - LUSH_CAVES
    chunk_chance: 50.0
    max_height: 0
    min_height: -64
    vein_blocks: 3
    chunk_veins: 1
  mythril_ore:
    block: mythril_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
#    biomes:
#    - LUSH_CAVES
    chunk_chance: 50.0
    max_height: 100
    min_height: 1
    vein_blocks: 3
    chunk_veins: 1
  mythril_ore_deepslate:
    block: mythril_ore_deepslate
    worlds:
    - world
    replaceable_blocks:
    - DEEPSLATE
    - TUFF
#    biomes:
#    - LUSH_CAVES
    chunk_chance: 50.0
    max_height: 0
    min_height: -64
    vein_blocks: 3
    chunk_veins: 1
  adamantite_ore:
    block: adamantite_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
    chunk_chance: 50.0
    max_height: 60
    min_height: 1
    vein_blocks: 1
    chunk_veins: 1
  adamantite_ore_deepslate:
    block: adamantite_ore_deepslate
    worlds:
    - world
    replaceable_blocks:
    - DEEPSLATE
    - TUFF
    chunk_chance: 50.0
    max_height: 0
    min_height: -64
    vein_blocks: 1
    chunk_veins: 1
  titanium_ore:
    block: titanium_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
    chunk_chance: 50.0
    max_height: 60
    min_height: 1
    vein_blocks: 1
    chunk_veins: 1
  titanium_ore_deepslate:
    block: titanium_ore_deepslate
    worlds:
    - world
    replaceable_blocks:
    - DEEPSLATE
    - TUFF
    chunk_chance: 50.0
    max_height: 0
    min_height: -64
    vein_blocks: 1
    chunk_veins: 1
  chlorophyte_ore:
    block: chlorophyte_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    - CALCITE
    - TUFF
#    biomes:
#    - JUNGLE
#    - SPARSE_JUNGLE
#    - BAMBOO_JUNGLE
    chunk_chance: 50.0
    max_height: 60
    min_height: 1
    vein_blocks: 3
    chunk_veins: 2
  chlorophyte_ore_deepslate:
    block: chlorophyte_ore_deepslate
    worlds:
    - world
    replaceable_blocks:
    - DEEPSLATE
    - TUFF
#    biomes:
#    - JUNGLE
#    - SPARSE_JUNGLE
#    - BAMBOO_JUNGLE
    chunk_chance: 50.0
    max_height: 0
    min_height: -64
    vein_blocks: 3
    chunk_veins: 2
  luminite_ore:
    block: luminite_ore
    worlds:
    - world_the_end
    replaceable_blocks:
    - END_STONE
    chunk_chance: 50.0
    max_height: 100
    min_height: 0
    vein_blocks: 1
    chunk_veins: 1