info:
  namespace: terraria
items:
  atlantic_cod:
    display_name: display-name-atlantic_cod
    lore:
    - lore-fish-common-ice
    resource:
      material: COD
      generate: true
      textures:
      - item/atlantic_cod
  bass:
    display_name: display-name-bass
    lore:
    - lore-fish-common
    resource:
      material: COD
      generate: true
      textures:
      - item/bass
  flounder:
    display_name: display-name-flounder
    lore:
    - lore-fish-common-desert
    resource:
      material: COD
      generate: true
      textures:
      - item/flounder
  neon_tetra:
    display_name: display-name-neon_tetra
    lore:
    - lore-fish-common-jungle
    - lore-fish-neon_tetra
    resource:
      material: COD
      generate: true
      textures:
      - item/neon_tetra
  red_snapper:
    display_name: display-name-red_snapper
    lore:
    - lore-fish-common-ocean
    resource:
      material: COD
      generate: true
      textures:
      - item/red_snapper
  rock_lobster:
    display_name: display-name-rock_lobster
    lore:
    - lore-fish-common-ocean
    - lore-fish-rock_lobster
    resource:
      material: COD
      generate: true
      textures:
      - item/rock_lobster
  shrimp:
    display_name: display-name-shrimp
    lore:
    - lore-fish-common-ocean
    resource:
      material: COD
      generate: true
      textures:
      - item/shrimp
  trout:
    display_name: display-name-trout
    lore:
    - lore-fish-common-ocean
    resource:
      material: COD
      generate: true
      textures:
      - item/trout
  tuna:
    display_name: display-name-tuna
    lore:
    - lore-fish-common-ocean
    resource:
      material: COD
      generate: true
      textures:
      - item/tuna
  armored_cavefish:
    display_name: display-name-armored_cavefish
    lore:
    - lore-fish-uncommon-underground
    resource:
      material: COD
      generate: true
      textures:
      - item/armored_cavefish
  blue_jellyfish:
    display_name: display-name-blue_jellyfish
    lore:
    - lore-fish-uncommon-cavern
    resource:
      material: COD
      generate: true
      textures:
      - item/blue_jellyfish
  crimson_tigerfish:
    display_name: display-name-crimson_tigerfish
    lore:
    - lore-fish-uncommon-crimson
    resource:
      material: COD
      generate: true
      textures:
      - item/crimson_tigerfish
  damselfish:
    display_name: display-name-damselfish
    lore:
    - lore-fish-uncommon-sky
    resource:
      material: COD
      generate: true
      textures:
      - item/damselfish
  double_cod:
    display_name: display-name-double_cod
    lore:
    - lore-fish-uncommon-jungle
    resource:
      material: COD
      generate: true
      textures:
      - item/double_cod
  ebonkoi:
    display_name: display-name-ebonkoi
    lore:
    - lore-fish-uncommon-corruption
    resource:
      material: COD
      generate: true
      textures:
      - item/ebonkoi
  frost_minnow:
    display_name: display-name-frost_minnow
    lore:
    - lore-fish-uncommon-ice
    resource:
      material: COD
      generate: true
      textures:
      - item/frost_minnow
  green_jellyfish:
    display_name: display-name-green_jellyfish
    lore:
    - lore-fish-uncommon-cavern
    resource:
      material: COD
      generate: true
      textures:
      - item/green_jellyfish
  hemopiranha:
    display_name: display-name-hemopiranha
    lore:
    - lore-fish-uncommon-crimson
    resource:
      material: COD
      generate: true
      textures:
      - item/hemopiranha
  honeyfin:
    display_name: display-name-honeyfin
    lore:
    - lore-fish-uncommon-honey
    resource:
      material: COD
      generate: true
      textures:
      - item/honeyfin
  pink_jellyfish:
    display_name: display-name-pink_jellyfish
    lore:
    - lore-fish-uncommon-ocean
    resource:
      material: COD
      generate: true
      textures:
      - item/pink_jellyfish
  specular_fish:
    display_name: display-name-specular_fish
    lore:
    - lore-fish-uncommon-underground
    resource:
      material: COD
      generate: true
      textures:
      - item/specular_fish
  stinkfish:
    display_name: display-name-stinkfish
    lore:
    - lore-fish-uncommon-underground
    resource:
      material: COD
      generate: true
      textures:
      - item/stinkfish
  variegated_lardfish:
    display_name: display-name-variegated_lardfish
    lore:
    - lore-fish-uncommon-jungle_underground
    resource:
      material: COD
      generate: true
      textures:
      - item/variegated_lardfish
  flarefin_koi:
    display_name: display-name-flarefin_koi
    lore:
    - lore-fish-rare-hell
    resource:
      material: COD
      generate: true
      textures:
      - item/flarefin_koi
  obsidifish:
    display_name: display-name-obsidifish
    lore:
    - lore-fish-rare-hell
    resource:
      material: COD
      generate: true
      textures:
      - item/obsidifish
  princess_fish:
    display_name: display-name-princess_fish
    lore:
    - lore-fish-rare-hallow
    resource:
      material: COD
      generate: true
      textures:
      - item/princess_fish
  prismite:
    display_name: display-name-prismite
    lore:
    - lore-fish-very_rare-hallow
    resource:
      material: COD
      generate: true
      textures:
      - item/prismite
  chaos_fish:
    display_name: display-name-chaos_fish
    lore:
    - lore-fish-legendary-hallow_underground
    resource:
      material: COD
      generate: true
      textures:
      - item/chaos_fish
  golden_carp:
    display_name: display-name-golden_carp
    lore:
    - lore-fish-legendary_underground
    - lore-fish-golden_carp
    resource:
      material: COD
      generate: true
      textures:
      - item/golden_carp