info:
  namespace: terraria
items:
  #copper_bar:
  tin_bar:
    display_name: display-name-tin_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/tin_bar
  lead_bar:
    display_name: display-name-lead_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/lead_bar
  #iron_bar
  silver_bar:
    display_name: display-name-silver_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/silver_bar
  tungsten_bar:
    display_name: display-name-tungsten_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/tungsten_bar
  #gold_bar
  platinum_bar:
    display_name: display-name-platinum_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/platinum_bar
#---FACE 2
  crimson_bar:
    display_name: display-name-crimson_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/crimson_bar
  demonite_bar:
    display_name: display-name-demonite_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/demonite_bar
  meteorite_bar:
    display_name: display-name-meteorite_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/meteorite_bar
  hellstone_bar:
    display_name: display-name-hellstone_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/hellstone_bar
#---FACE 3
  cobalt_bar:
    display_name: display-name-cobalt_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/cobalt_bar
  palladium_bar:
    display_name: display-name-palladium_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/palladium_bar
  orichalcum_bar:
    display_name: display-name-orichalcum_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/orichalcum_bar
  mythril_bar:
    display_name: display-name-mythril_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/mythril_bar
  adamantite_bar:
    display_name: display-name-adamantite_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/adamantite_bar
  titanium_bar:
    display_name: display-name-titanium_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/titanium_bar
#---FACE 4
  chlorophyte_bar:
    display_name: display-name-chlorophyte_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/chlorophyte_bar
  #shroomite_bar
  luminite_bar:
    display_name: display-name-luminite_bar
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/luminite_bar
#RAWS
  #raw_copper:
  raw_tin:
    display_name: display-name-raw_tin
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_tin
  raw_lead:
    display_name: display-name-raw_lead
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_lead
  #raw_iron
  raw_silver:
    display_name: display-name-raw_silver
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_silver
  #raw_gold
  raw_tungsten:
    display_name: display-name-raw_tungsten
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_tungsten
  raw_platinum:
    display_name: display-name-raw_platinum
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_platinum
  #---FACE 2
  raw_crimson:
    display_name: display-name-raw_crimson
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_crimson
  raw_demonite:
    display_name: display-name-raw_demonite
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_demonite
  raw_meteorite:
    display_name: display-name-raw_meteorite
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_meteorite
  raw_hellstone:
    display_name: display-name-raw_hellstone
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_hellstone
  #---FACE 3
  raw_cobalt:
    display_name: display-name-raw_cobalt
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_cobalt
  raw_palladium:
    display_name: display-name-raw_palladium
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_palladium
  raw_orichalcum:
    display_name: display-name-raw_orichalcum
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_orichalcum
  raw_mythril:
    display_name: display-name-raw_mythril
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_mythril
  raw_adamantite:
    display_name: display-name-raw_adamantite
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_adamantite
  raw_titanium:
    display_name: display-name-raw_titanium
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_titanium
  #---FACE 4
  raw_chlorophyte:
    display_name: display-name-raw_chlorophyte
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_chlorophyte
  #raw_shroomite
  raw_luminite:
    display_name: display-name-raw_luminite
    resource:
      material: PAPER
      generate: true
      textures:
      - item/raw_luminite